/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) rocket_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_triusolve CASADI_PREFIX(triusolve)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_triusolve(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x, int tr, int unity,
    casadi_int nrhs) {
  casadi_int nrow, ncol, r, c, k, rhs;
  const casadi_int *colind, *row;
  nrow = sp_a[0];
  ncol = sp_a[1];
  colind = sp_a + 2;
  row = colind + ncol + 1;
  for (rhs = 0; rhs < nrhs; ++rhs) {
    if (unity) {
      if (tr) {
        for (c = 0; c < ncol; ++c) {
          for (k = colind[c]; k < colind[c+1]; ++k) {
            x[c] += nz_a[k] * x[row[k]];
          }
        }
      } else {
        for (c = ncol; c-- > 0; ) {
          for (k = colind[c + 1]; k-- > colind[c]; ) {
            x[row[k]] += nz_a[k] * x[c];
          }
        }
      }
    } else {
      if (tr) {
        for (c = 0; c < ncol; ++c) {
          for (k = colind[c]; k < colind[c+1]; ++k) {
            r = row[k];
            if (r == c) {
              x[c] /= nz_a[k];
            } else {
              x[c] -= nz_a[k] * x[r];
            }
          }
        }
      } else {
        for (c = ncol; c-- > 0; ) {
          for (k = colind[c + 1]; k-- > colind[c]; ) {
            r = row[k];
            if (r == c) {
              x[r] /= nz_a[k];
            } else {
              x[r] -= nz_a[k] * x[c];
            }
          }
        }
      }
    }
    x += nrow;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

static const casadi_int casadi_s0[9] = 
  {3, 3, 0, 1, 2, 3, 0, 1,
  2};
static const casadi_int casadi_s1[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[3] = {15, 1, 1};
static const casadi_int casadi_s3[3] = {3, 1, 1};
static const casadi_int casadi_s4[3] = {0, 1, 1};
static const casadi_int casadi_s5[19] = 
  {18, 1, 0, 15, 0, 4, 5, 6,
  7, 8, 9, 10, 11, 12, 13, 14,
  15, 16, 17};

static const casadi_real casadi_c0[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};
static const casadi_real casadi_c1[3] = {0., 0., -20.};
static const casadi_real casadi_c2[3] = {0., 0., -9.8100000000000005e+00};

static const casadi_real casadi_zeros[15] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0.};

/* rocket_expl_vde_adj:(i0[15],i1[15],i2[3],i3[0])->(o0[18x1,15nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, *w02=w+6, *w03=w+9, w04, *w05=w+13, *w06=w+22, w07, w08, w09, w10;
  casadi_real w11, w12, *w13=w+31, *w14=w+34, *w15=w+37, *w18=w+75, *w19=w+89, *w20=w+92, *w21=w+96, *w22=w+99, *w23=w+102, w24;
  casadi_real w25, w26, w27, w28, w29, *w30=w+111, *w31=w+114, *w32=w+117, *w33=w+126, *w34=w+129, w35, w36;
  casadi_real w37, w38, w39, w40, w41, w42, *w43=w+140, *w44=w+149, w45, w46, w47, w48;
  casadi_real w49, w50, w51, *w52=w+160, *w53=w+164, *w54=w+168, *w55=w+172, *w56=w+176, *w57=w+180, *w58=w+196, *w59=w+212;
  const casadi_real *cr, *cs, *ct, *wr05, *wr16, *wr17;
  /* #0: @0 = 0.5 */
  w00 = 5.0000000000000000e-01;
  /* #1: @1 = 20.25 */
  w01 = 2.0250000000000000e+01;
  /* #2: @2 = input[0][4] */
  casadi_copy(arg[0] ? arg[0]+11 : 0, 3, w02);
  /* #3: @3 = zeros(3x1) */
  casadi_clear(w03, 3);
  /* #4: @4 = @2[2] */
  for (rr=(&w04), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #5: @5 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr05 = casadi_c0;
  /* #6: @6 = all_1e-05(3x3,3nz) */
  casadi_fill(w06, 3, 1.0000000000000001e-05);
  /* #7: @7 = 0.25 */
  w07 = 2.5000000000000000e-01;
  /* #8: @8 = input[0][0] */
  w08 = arg[0] ? arg[0][0] : 0;
  /* #9: @9 = (@7*@8) */
  w09  = (w07*w08);
  /* #10: @9 = (@1*@9) */
  w09  = (w01*w09);
  /* #11: @10 = 2500 */
  w10 = 2500.;
  /* #12: @11 = 0.0833333 */
  w11 = 8.3333333333333329e-02;
  /* #13: @12 = (@11*@8) */
  w12  = (w11*w08);
  /* #14: @12 = (@10*@12) */
  w12  = (w10*w12);
  /* #15: @9 = (@9+@12) */
  w09 += w12;
  /* #16: @12 = (@0*@8) */
  w12  = (w00*w08);
  /* #17: @12 = (@1*@12) */
  w12  = (w01*w12);
  /* #18: @13 = vertcat(@9, @9, @12) */
  rr=w13;
  *rr++ = w09;
  *rr++ = w09;
  *rr++ = w12;
  /* #19: @14 = sparsity_cast(@13) */
  casadi_copy(w13, 3, w14);
  /* #20: @6 = (@6+@14) */
  for (i=0, rr=w06, cs=w14; i<3; ++i) (*rr++) += (*cs++);
  /* #21: @5 = (@6\@5) */
  casadi_copy(wr05, 9, w05);
  casadi_triusolve(casadi_s0, w06, w05, 0, 0, 3);
  /* #22: @15 = @5' */
  for (i=0, rr=w15, cs=w05; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #23: @9 = input[0][5] */
  w09 = arg[0] ? arg[0][14] : 0;
  /* #24: @16 = input[1][0] */
  wr16 = arg[1] ? arg[1] : casadi_zeros;
  /* #25: {@17, NULL} = vertsplit(@16) */
  wr17 = wr16;
  /* #26: @18 = (@9*@17) */
  for (i=0, rr=w18, cs=wr17; i<14; ++i) (*rr++)  = (w09*(*cs++));
  /* #27: {@9, @14, @19, @20, @21} = vertsplit(@18) */
  w09 = w18[0];
  casadi_copy(w18+1, 3, w14);
  casadi_copy(w18+4, 3, w19);
  casadi_copy(w18+7, 4, w20);
  casadi_copy(w18+11, 3, w21);
  /* #28: @22 = mac(@15,@21,@3) */
  casadi_copy(w03, 3, w22);
  for (i=0, rr=w22; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w15+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #29: @23 = (-@22) */
  for (i=0, rr=w23, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #30: {@12, @24, @25} = vertsplit(@23) */
  w12 = w23[0];
  w24 = w23[1];
  w25 = w23[2];
  /* #31: @26 = (@4*@24) */
  w26  = (w04*w24);
  /* #32: @27 = @2[1] */
  for (rr=(&w27), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #33: @28 = (@27*@25) */
  w28  = (w27*w25);
  /* #34: @26 = (@26-@28) */
  w26 -= w28;
  /* #35: @23 = @3; (@23[0] += @26) */
  casadi_copy(w03, 3, w23);
  for (rr=w23+0, cs=(&w26); rr!=w23+1; rr+=1) *rr += *cs++;
  /* #36: @26 = @2[0] */
  for (rr=(&w26), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #37: @28 = (@26*@25) */
  w28  = (w26*w25);
  /* #38: @29 = (@4*@12) */
  w29  = (w04*w12);
  /* #39: @28 = (@28-@29) */
  w28 -= w29;
  /* #40: (@23[1] += @28) */
  for (rr=w23+1, cs=(&w28); rr!=w23+2; rr+=1) *rr += *cs++;
  /* #41: @28 = (@27*@12) */
  w28  = (w27*w12);
  /* #42: @29 = (@26*@24) */
  w29  = (w26*w24);
  /* #43: @28 = (@28-@29) */
  w28 -= w29;
  /* #44: (@23[2] += @28) */
  for (rr=w23+2, cs=(&w28); rr!=w23+3; rr+=1) *rr += *cs++;
  /* #45: @30 = (@2*@23) */
  for (i=0, rr=w30, cr=w02, cs=w23; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #46: @31 = zeros(3x3,3nz) */
  casadi_clear(w31, 3);
  /* #47: @32 = zeros(3x3) */
  casadi_clear(w32, 9);
  /* #48: @33 = [0, 0, -20] */
  casadi_copy(casadi_c1, 3, w33);
  /* #49: @28 = @33[1] */
  for (rr=(&w28), cs=w33+1; cs!=w33+2; cs+=1) *rr++ = *cs;
  /* #50: @34 = input[2][0] */
  casadi_copy(arg[2], 3, w34);
  /* #51: @29 = @34[2] */
  for (rr=(&w29), cs=w34+2; cs!=w34+3; cs+=1) *rr++ = *cs;
  /* #52: @35 = (@28*@29) */
  w35  = (w28*w29);
  /* #53: @36 = @33[2] */
  for (rr=(&w36), cs=w33+2; cs!=w33+3; cs+=1) *rr++ = *cs;
  /* #54: @37 = @34[1] */
  for (rr=(&w37), cs=w34+1; cs!=w34+2; cs+=1) *rr++ = *cs;
  /* #55: @38 = (@36*@37) */
  w38  = (w36*w37);
  /* #56: @35 = (@35-@38) */
  w35 -= w38;
  /* #57: @38 = @34[0] */
  for (rr=(&w38), cs=w34+0; cs!=w34+1; cs+=1) *rr++ = *cs;
  /* #58: @39 = (@36*@38) */
  w39  = (w36*w38);
  /* #59: @40 = @33[0] */
  for (rr=(&w40), cs=w33+0; cs!=w33+1; cs+=1) *rr++ = *cs;
  /* #60: @29 = (@40*@29) */
  w29  = (w40*w29);
  /* #61: @39 = (@39-@29) */
  w39 -= w29;
  /* #62: @37 = (@40*@37) */
  w37  = (w40*w37);
  /* #63: @38 = (@28*@38) */
  w38  = (w28*w38);
  /* #64: @37 = (@37-@38) */
  w37 -= w38;
  /* #65: @33 = vertcat(@35, @39, @37) */
  rr=w33;
  *rr++ = w35;
  *rr++ = w39;
  *rr++ = w37;
  /* #66: @2 = (@13*@2) */
  for (i=0, rr=w02, cr=w13, cs=w02; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #67: @35 = @2[2] */
  for (rr=(&w35), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #68: @39 = (@27*@35) */
  w39  = (w27*w35);
  /* #69: @37 = @2[1] */
  for (rr=(&w37), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #70: @38 = (@4*@37) */
  w38  = (w04*w37);
  /* #71: @39 = (@39-@38) */
  w39 -= w38;
  /* #72: @38 = @2[0] */
  for (rr=(&w38), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #73: @29 = (@4*@38) */
  w29  = (w04*w38);
  /* #74: @41 = (@26*@35) */
  w41  = (w26*w35);
  /* #75: @29 = (@29-@41) */
  w29 -= w41;
  /* #76: @41 = (@26*@37) */
  w41  = (w26*w37);
  /* #77: @42 = (@27*@38) */
  w42  = (w27*w38);
  /* #78: @41 = (@41-@42) */
  w41 -= w42;
  /* #79: @2 = vertcat(@39, @29, @41) */
  rr=w02;
  *rr++ = w39;
  *rr++ = w29;
  *rr++ = w41;
  /* #80: @33 = (@33-@2) */
  for (i=0, rr=w33, cs=w02; i<3; ++i) (*rr++) -= (*cs++);
  /* #81: @2 = @33' */
  casadi_copy(w33, 3, w02);
  /* #82: @43 = mac(@21,@2,@32) */
  casadi_copy(w32, 9, w43);
  for (i=0, rr=w43; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w21+j, ct=w02+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #83: @43 = (@6'\@43) */
  casadi_triusolve(casadi_s0, w06, w43, 1, 0, 3);
  /* #84: @31 = mac(@43,@15,@31) */
  casadi_mtimes(w43, casadi_s1, w15, casadi_s1, w31, casadi_s0, w, 0);
  /* #85: @31 = (-@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) *rr++ = (- *cs++ );
  /* #86: @31 = nonzeros(@31) */
  /* #87: @30 = (@30+@31) */
  for (i=0, rr=w30, cs=w31; i<3; ++i) (*rr++) += (*cs++);
  /* #88: {@39, @29, @41} = vertsplit(@30) */
  w39 = w30[0];
  w29 = w30[1];
  w41 = w30[2];
  /* #89: @41 = (@1*@41) */
  w41  = (w01*w41);
  /* #90: @41 = (@0*@41) */
  w41  = (w00*w41);
  /* #91: @42 = (@10*@29) */
  w42  = (w10*w29);
  /* #92: @42 = (@11*@42) */
  w42  = (w11*w42);
  /* #93: @41 = (@41+@42) */
  w41 += w42;
  /* #94: @29 = (@1*@29) */
  w29  = (w01*w29);
  /* #95: @29 = (@7*@29) */
  w29  = (w07*w29);
  /* #96: @41 = (@41+@29) */
  w41 += w29;
  /* #97: @10 = (@10*@39) */
  w10 *= w39;
  /* #98: @11 = (@11*@10) */
  w11 *= w10;
  /* #99: @41 = (@41+@11) */
  w41 += w11;
  /* #100: @1 = (@1*@39) */
  w01 *= w39;
  /* #101: @7 = (@7*@1) */
  w07 *= w01;
  /* #102: @41 = (@41+@7) */
  w41 += w07;
  /* #103: @7 = 1 */
  w07 = 1.;
  /* #104: @44 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 4, w44);
  /* #105: @1 = @44[2] */
  for (rr=(&w01), cs=w44+2; cs!=w44+3; cs+=1) *rr++ = *cs;
  /* #106: @39 = sq(@1) */
  w39 = casadi_sq( w01 );
  /* #107: @11 = @44[3] */
  for (rr=(&w11), cs=w44+3; cs!=w44+4; cs+=1) *rr++ = *cs;
  /* #108: @10 = sq(@11) */
  w10 = casadi_sq( w11 );
  /* #109: @29 = (@39+@10) */
  w29  = (w39+w10);
  /* #110: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #111: @29 = (@7-@29) */
  w29  = (w07-w29);
  /* #112: @42 = @44[1] */
  for (rr=(&w42), cs=w44+1; cs!=w44+2; cs+=1) *rr++ = *cs;
  /* #113: @45 = (@42*@1) */
  w45  = (w42*w01);
  /* #114: @46 = @44[0] */
  for (rr=(&w46), cs=w44+0; cs!=w44+1; cs+=1) *rr++ = *cs;
  /* #115: @47 = (@46*@11) */
  w47  = (w46*w11);
  /* #116: @48 = (@45-@47) */
  w48  = (w45-w47);
  /* #117: @48 = (2.*@48) */
  w48 = (2.* w48 );
  /* #118: @49 = (@42*@11) */
  w49  = (w42*w11);
  /* #119: @50 = (@46*@1) */
  w50  = (w46*w01);
  /* #120: @51 = (@49+@50) */
  w51  = (w49+w50);
  /* #121: @51 = (2.*@51) */
  w51 = (2.* w51 );
  /* #122: @30 = horzcat(@29, @48, @51) */
  rr=w30;
  *rr++ = w29;
  *rr++ = w48;
  *rr++ = w51;
  /* #123: @30 = @30' */
  /* #124: @45 = (@45+@47) */
  w45 += w47;
  /* #125: @45 = (2.*@45) */
  w45 = (2.* w45 );
  /* #126: @47 = sq(@42) */
  w47 = casadi_sq( w42 );
  /* #127: @10 = (@47+@10) */
  w10  = (w47+w10);
  /* #128: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #129: @10 = (@7-@10) */
  w10  = (w07-w10);
  /* #130: @29 = (@1*@11) */
  w29  = (w01*w11);
  /* #131: @48 = (@46*@42) */
  w48  = (w46*w42);
  /* #132: @51 = (@29-@48) */
  w51  = (w29-w48);
  /* #133: @51 = (2.*@51) */
  w51 = (2.* w51 );
  /* #134: @31 = horzcat(@45, @10, @51) */
  rr=w31;
  *rr++ = w45;
  *rr++ = w10;
  *rr++ = w51;
  /* #135: @31 = @31' */
  /* #136: @49 = (@49-@50) */
  w49 -= w50;
  /* #137: @49 = (2.*@49) */
  w49 = (2.* w49 );
  /* #138: @29 = (@29+@48) */
  w29 += w48;
  /* #139: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #140: @47 = (@47+@39) */
  w47 += w39;
  /* #141: @47 = (2.*@47) */
  w47 = (2.* w47 );
  /* #142: @7 = (@7-@47) */
  w07 -= w47;
  /* #143: @6 = horzcat(@49, @29, @7) */
  rr=w06;
  *rr++ = w49;
  *rr++ = w29;
  *rr++ = w07;
  /* #144: @6 = @6' */
  /* #145: @43 = horzcat(@30, @31, @6) */
  rr=w43;
  for (i=0, cs=w30; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w06; i<3; ++i) *rr++ = *cs++;
  /* #146: @15 = @43' */
  for (i=0, rr=w15, cs=w43; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #147: @15 = (@15/@8) */
  for (i=0, rr=w15; i<9; ++i) (*rr++) /= w08;
  /* #148: @43 = (@15/@8) */
  for (i=0, rr=w43, cr=w15; i<9; ++i) (*rr++)  = ((*cr++)/w08);
  /* #149: @43 = (-@43) */
  for (i=0, rr=w43, cs=w43; i<9; ++i) *rr++ = (- *cs++ );
  /* #150: @30 = @34' */
  casadi_copy(w34, 3, w30);
  /* #151: @32 = mac(@19,@30,@32) */
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w19+j, ct=w30+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #152: @49 = dot(@43, @32) */
  w49 = casadi_dot(9, w43, w32);
  /* #153: @41 = (@41+@49) */
  w41 += w49;
  /* #154: output[0][0] = @41 */
  if (res[0]) res[0][0] = w41;
  /* #155: output[0][1] = @14 */
  if (res[0]) casadi_copy(w14, 3, res[0]+1);
  /* #156: @52 = zeros(4x1) */
  casadi_clear(w52, 4);
  /* #157: @41 = 0 */
  w41 = 0.;
  /* #158: @49 = (-@26) */
  w49 = (- w26 );
  /* #159: @29 = (-@27) */
  w29 = (- w27 );
  /* #160: @7 = (-@4) */
  w07 = (- w04 );
  /* #161: @53 = horzcat(@41, @49, @29, @7) */
  rr=w53;
  *rr++ = w41;
  *rr++ = w49;
  *rr++ = w29;
  *rr++ = w07;
  /* #162: @53 = @53' */
  /* #163: @54 = horzcat(@26, @41, @4, @29) */
  rr=w54;
  *rr++ = w26;
  *rr++ = w41;
  *rr++ = w04;
  *rr++ = w29;
  /* #164: @54 = @54' */
  /* #165: @55 = horzcat(@27, @7, @41, @26) */
  rr=w55;
  *rr++ = w27;
  *rr++ = w07;
  *rr++ = w41;
  *rr++ = w26;
  /* #166: @55 = @55' */
  /* #167: @56 = horzcat(@4, @27, @49, @41) */
  rr=w56;
  *rr++ = w04;
  *rr++ = w27;
  *rr++ = w49;
  *rr++ = w41;
  /* #168: @56 = @56' */
  /* #169: @57 = horzcat(@53, @54, @55, @56) */
  rr=w57;
  for (i=0, cs=w53; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w54; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w56; i<4; ++i) *rr++ = *cs++;
  /* #170: @58 = @57' */
  for (i=0, rr=w58, cs=w57; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #171: @58 = (@0*@58) */
  for (i=0, rr=w58, cs=w58; i<16; ++i) (*rr++)  = (w00*(*cs++));
  /* #172: @57 = @58' */
  for (i=0, rr=w57, cs=w58; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #173: @53 = mac(@57,@20,@52) */
  casadi_copy(w52, 4, w53);
  for (i=0, rr=w53; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w57+j, ct=w20+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #174: @32 = (@32/@8) */
  for (i=0, rr=w32; i<9; ++i) (*rr++) /= w08;
  /* #175: @43 = @32' */
  for (i=0, rr=w43, cs=w32; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #176: {@14, @30, @31} = horzsplit(@43) */
  casadi_copy(w43, 3, w14);
  casadi_copy(w43+3, 3, w30);
  casadi_copy(w43+6, 3, w31);
  /* #177: @31 = @31' */
  /* #178: {@8, @4, @27} = horzsplit(@31) */
  w08 = w31[0];
  w04 = w31[1];
  w27 = w31[2];
  /* #179: @4 = (2.*@4) */
  w04 = (2.* w04 );
  /* #180: @49 = (@42*@4) */
  w49  = (w42*w04);
  /* #181: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #182: @41 = (@1*@8) */
  w41  = (w01*w08);
  /* #183: @49 = (@49-@41) */
  w49 -= w41;
  /* #184: @30 = @30' */
  /* #185: {@41, @7, @26} = horzsplit(@30) */
  w41 = w30[0];
  w07 = w30[1];
  w26 = w30[2];
  /* #186: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #187: @29 = (@42*@26) */
  w29  = (w42*w26);
  /* #188: @49 = (@49-@29) */
  w49 -= w29;
  /* #189: @41 = (2.*@41) */
  w41 = (2.* w41 );
  /* #190: @29 = (@11*@41) */
  w29  = (w11*w41);
  /* #191: @49 = (@49+@29) */
  w49 += w29;
  /* #192: @14 = @14' */
  /* #193: {@29, @47, @39} = horzsplit(@14) */
  w29 = w14[0];
  w47 = w14[1];
  w39 = w14[2];
  /* #194: @39 = (2.*@39) */
  w39 = (2.* w39 );
  /* #195: @48 = (@1*@39) */
  w48  = (w01*w39);
  /* #196: @49 = (@49+@48) */
  w49 += w48;
  /* #197: @47 = (2.*@47) */
  w47 = (2.* w47 );
  /* #198: @48 = (@11*@47) */
  w48  = (w11*w47);
  /* #199: @49 = (@49-@48) */
  w49 -= w48;
  /* #200: (@53[0] += @49) */
  for (rr=w53+0, cs=(&w49); rr!=w53+1; rr+=1) *rr += *cs++;
  /* #201: @49 = (2.*@42) */
  w49 = (2.* w42 );
  /* #202: @27 = (-@27) */
  w27 = (- w27 );
  /* #203: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #204: @48 = (@49*@27) */
  w48  = (w49*w27);
  /* #205: @50 = (@46*@4) */
  w50  = (w46*w04);
  /* #206: @48 = (@48+@50) */
  w48 += w50;
  /* #207: @50 = (@11*@8) */
  w50  = (w11*w08);
  /* #208: @48 = (@48+@50) */
  w48 += w50;
  /* #209: @50 = (@46*@26) */
  w50  = (w46*w26);
  /* #210: @48 = (@48-@50) */
  w48 -= w50;
  /* #211: @7 = (-@7) */
  w07 = (- w07 );
  /* #212: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #213: @49 = (@49*@7) */
  w49 *= w07;
  /* #214: @48 = (@48+@49) */
  w48 += w49;
  /* #215: @49 = (@1*@41) */
  w49  = (w01*w41);
  /* #216: @48 = (@48+@49) */
  w48 += w49;
  /* #217: @49 = (@11*@39) */
  w49  = (w11*w39);
  /* #218: @48 = (@48+@49) */
  w48 += w49;
  /* #219: @49 = (@1*@47) */
  w49  = (w01*w47);
  /* #220: @48 = (@48+@49) */
  w48 += w49;
  /* #221: (@53[1] += @48) */
  for (rr=w53+1, cs=(&w48); rr!=w53+2; rr+=1) *rr += *cs++;
  /* #222: @48 = (@1*@4) */
  w48  = (w01*w04);
  /* #223: @49 = (@42*@8) */
  w49  = (w42*w08);
  /* #224: @48 = (@48+@49) */
  w48 += w49;
  /* #225: @49 = (@1*@26) */
  w49  = (w01*w26);
  /* #226: @48 = (@48+@49) */
  w48 += w49;
  /* #227: @49 = (2.*@11) */
  w49 = (2.* w11 );
  /* #228: @7 = (@49*@7) */
  w07  = (w49*w07);
  /* #229: @48 = (@48+@7) */
  w48 += w07;
  /* #230: @7 = (@46*@41) */
  w07  = (w46*w41);
  /* #231: @48 = (@48+@7) */
  w48 += w07;
  /* #232: @7 = (@42*@39) */
  w07  = (w42*w39);
  /* #233: @48 = (@48+@7) */
  w48 += w07;
  /* #234: @7 = (@46*@47) */
  w07  = (w46*w47);
  /* #235: @48 = (@48-@7) */
  w48 -= w07;
  /* #236: @29 = (-@29) */
  w29 = (- w29 );
  /* #237: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #238: @49 = (@49*@29) */
  w49 *= w29;
  /* #239: @48 = (@48+@49) */
  w48 += w49;
  /* #240: (@53[3] += @48) */
  for (rr=w53+3, cs=(&w48); rr!=w53+4; rr+=1) *rr += *cs++;
  /* #241: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #242: @27 = (@1*@27) */
  w27  = (w01*w27);
  /* #243: @4 = (@11*@4) */
  w04  = (w11*w04);
  /* #244: @27 = (@27+@4) */
  w27 += w04;
  /* #245: @8 = (@46*@8) */
  w08  = (w46*w08);
  /* #246: @27 = (@27-@8) */
  w27 -= w08;
  /* #247: @11 = (@11*@26) */
  w11 *= w26;
  /* #248: @27 = (@27+@11) */
  w27 += w11;
  /* #249: @41 = (@42*@41) */
  w41  = (w42*w41);
  /* #250: @27 = (@27+@41) */
  w27 += w41;
  /* #251: @46 = (@46*@39) */
  w46 *= w39;
  /* #252: @27 = (@27+@46) */
  w27 += w46;
  /* #253: @42 = (@42*@47) */
  w42 *= w47;
  /* #254: @27 = (@27+@42) */
  w27 += w42;
  /* #255: @1 = (@1*@29) */
  w01 *= w29;
  /* #256: @27 = (@27+@1) */
  w27 += w01;
  /* #257: (@53[2] += @27) */
  for (rr=w53+2, cs=(&w27); rr!=w53+3; rr+=1) *rr += *cs++;
  /* #258: output[0][2] = @53 */
  if (res[0]) casadi_copy(w53, 4, res[0]+4);
  /* #259: @27 = (@37*@25) */
  w27  = (w37*w25);
  /* #260: @1 = (@35*@24) */
  w01  = (w35*w24);
  /* #261: @27 = (@27-@1) */
  w27 -= w01;
  /* #262: @14 = @3; (@14[0] += @27) */
  casadi_copy(w03, 3, w14);
  for (rr=w14+0, cs=(&w27); rr!=w14+1; rr+=1) *rr += *cs++;
  /* #263: @24 = (@38*@24) */
  w24  = (w38*w24);
  /* #264: @37 = (@37*@12) */
  w37 *= w12;
  /* #265: @24 = (@24-@37) */
  w24 -= w37;
  /* #266: (@14[2] += @24) */
  for (rr=w14+2, cs=(&w24); rr!=w14+3; rr+=1) *rr += *cs++;
  /* #267: @13 = (@13*@23) */
  for (i=0, rr=w13, cs=w23; i<3; ++i) (*rr++) *= (*cs++);
  /* #268: @14 = (@14+@13) */
  for (i=0, rr=w14, cs=w13; i<3; ++i) (*rr++) += (*cs++);
  /* #269: @35 = (@35*@12) */
  w35 *= w12;
  /* #270: @38 = (@38*@25) */
  w38 *= w25;
  /* #271: @35 = (@35-@38) */
  w35 -= w38;
  /* #272: (@14[1] += @35) */
  for (rr=w14+1, cs=(&w35); rr!=w14+2; rr+=1) *rr += *cs++;
  /* #273: @57 = zeros(4x4) */
  casadi_clear(w57, 16);
  /* #274: @53 = @44' */
  casadi_copy(w44, 4, w53);
  /* #275: @57 = mac(@20,@53,@57) */
  for (i=0, rr=w57; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w20+j, ct=w53+i*1; k<1; ++k) *rr += cs[k*4]**ct++;
  /* #276: @57 = (@0*@57) */
  for (i=0, rr=w57, cs=w57; i<16; ++i) (*rr++)  = (w00*(*cs++));
  /* #277: @59 = @57' */
  for (i=0, rr=w59, cs=w57; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #278: {@20, @53, @54, @55} = horzsplit(@59) */
  casadi_copy(w59, 4, w20);
  casadi_copy(w59+4, 4, w53);
  casadi_copy(w59+8, 4, w54);
  casadi_copy(w59+12, 4, w55);
  /* #279: @55 = @55' */
  /* #280: {@0, @35, @38, NULL} = horzsplit(@55) */
  w00 = w55[0];
  w35 = w55[1];
  w38 = w55[2];
  /* #281: @54 = @54' */
  /* #282: {@25, @12, NULL, @24} = horzsplit(@54) */
  w25 = w54[0];
  w12 = w54[1];
  w24 = w54[3];
  /* #283: @0 = (@0-@12) */
  w00 -= w12;
  /* #284: @53 = @53' */
  /* #285: {@12, NULL, @37, @27} = horzsplit(@53) */
  w12 = w53[0];
  w37 = w53[2];
  w27 = w53[3];
  /* #286: @0 = (@0+@37) */
  w00 += w37;
  /* #287: @20 = @20' */
  /* #288: {NULL, @37, @1, @29} = horzsplit(@20) */
  w37 = w20[1];
  w01 = w20[2];
  w29 = w20[3];
  /* #289: @0 = (@0-@29) */
  w00 -= w29;
  /* #290: (@14[2] += @0) */
  for (rr=w14+2, cs=(&w00); rr!=w14+3; rr+=1) *rr += *cs++;
  /* #291: @35 = (@35+@25) */
  w35 += w25;
  /* #292: @35 = (@35-@27) */
  w35 -= w27;
  /* #293: @35 = (@35-@1) */
  w35 -= w01;
  /* #294: (@14[1] += @35) */
  for (rr=w14+1, cs=(&w35); rr!=w14+2; rr+=1) *rr += *cs++;
  /* #295: @24 = (@24-@38) */
  w24 -= w38;
  /* #296: @24 = (@24+@12) */
  w24 += w12;
  /* #297: @24 = (@24-@37) */
  w24 -= w37;
  /* #298: (@14[0] += @24) */
  for (rr=w14+0, cs=(&w24); rr!=w14+1; rr+=1) *rr += *cs++;
  /* #299: output[0][3] = @14 */
  if (res[0]) casadi_copy(w14, 3, res[0]+8);
  /* #300: @24 = -0.000339789 */
  w24 = -3.3978933061501872e-04;
  /* #301: @37 = ||@34||_F */
  w37 = casadi_norm_2(3, w34);
  /* #302: @12 = (@24*@37) */
  w12  = (w24*w37);
  /* #303: @14 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+4 : 0, 3, w14);
  /* #304: @13 = [0, 0, -9.81] */
  casadi_copy(casadi_c2, 3, w13);
  /* #305: @23 = mac(@15,@34,@3) */
  casadi_copy(w03, 3, w23);
  for (i=0, rr=w23; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w15+j, ct=w34+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #306: @13 = (@13+@23) */
  for (i=0, rr=w13, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #307: @52 = mac(@58,@44,@52) */
  for (i=0, rr=w52; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w58+j, ct=w44+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #308: @23 = mac(@5,@33,@3) */
  casadi_copy(w03, 3, w23);
  for (i=0, rr=w23; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w05+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #309: @18 = vertcat(@12, @14, @13, @52, @23) */
  rr=w18;
  *rr++ = w12;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w52; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  /* #310: @12 = dot(@18, @17) */
  w12 = casadi_dot(14, w18, wr17);
  /* #311: output[0][4] = @12 */
  if (res[0]) res[0][11] = w12;
  /* #312: {@12, @38, @35} = vertsplit(@22) */
  w12 = w22[0];
  w38 = w22[1];
  w35 = w22[2];
  /* #313: @1 = (@36*@38) */
  w01  = (w36*w38);
  /* #314: @27 = (@28*@35) */
  w27  = (w28*w35);
  /* #315: @1 = (@1-@27) */
  w01 -= w27;
  /* #316: @22 = @3; (@22[0] += @1) */
  casadi_copy(w03, 3, w22);
  for (rr=w22+0, cs=(&w01); rr!=w22+1; rr+=1) *rr += *cs++;
  /* #317: @35 = (@40*@35) */
  w35  = (w40*w35);
  /* #318: @36 = (@36*@12) */
  w36 *= w12;
  /* #319: @35 = (@35-@36) */
  w35 -= w36;
  /* #320: (@22[1] += @35) */
  for (rr=w22+1, cs=(&w35); rr!=w22+2; rr+=1) *rr += *cs++;
  /* #321: @28 = (@28*@12) */
  w28 *= w12;
  /* #322: @40 = (@40*@38) */
  w40 *= w38;
  /* #323: @28 = (@28-@40) */
  w28 -= w40;
  /* #324: (@22[2] += @28) */
  for (rr=w22+2, cs=(&w28); rr!=w22+3; rr+=1) *rr += *cs++;
  /* #325: @5 = @15' */
  for (i=0, rr=w05, cs=w15; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #326: @3 = mac(@5,@19,@3) */
  for (i=0, rr=w03; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w05+j, ct=w19+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #327: @22 = (@22+@3) */
  for (i=0, rr=w22, cs=w03; i<3; ++i) (*rr++) += (*cs++);
  /* #328: @24 = (@24*@9) */
  w24 *= w09;
  /* #329: @24 = (@24/@37) */
  w24 /= w37;
  /* #330: @34 = (@24*@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) (*rr++)  = (w24*(*cs++));
  /* #331: @22 = (@22+@34) */
  for (i=0, rr=w22, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #332: output[0][5] = @22 */
  if (res[0]) casadi_copy(w22, 3, res[0]+12);
  return 0;
}

CASADI_SYMBOL_EXPORT int rocket_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rocket_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rocket_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rocket_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rocket_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rocket_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rocket_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void rocket_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rocket_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int rocket_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real rocket_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rocket_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rocket_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rocket_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rocket_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rocket_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 228;
  return 0;
}

CASADI_SYMBOL_EXPORT int rocket_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 6*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 228*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
