/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) rocket_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_triusolve CASADI_PREFIX(triusolve)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_triusolve(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x, int tr, int unity,
    casadi_int nrhs) {
  casadi_int nrow, ncol, r, c, k, rhs;
  const casadi_int *colind, *row;
  nrow = sp_a[0];
  ncol = sp_a[1];
  colind = sp_a + 2;
  row = colind + ncol + 1;
  for (rhs = 0; rhs < nrhs; ++rhs) {
    if (unity) {
      if (tr) {
        for (c = 0; c < ncol; ++c) {
          for (k = colind[c]; k < colind[c+1]; ++k) {
            x[c] += nz_a[k] * x[row[k]];
          }
        }
      } else {
        for (c = ncol; c-- > 0; ) {
          for (k = colind[c + 1]; k-- > colind[c]; ) {
            x[row[k]] += nz_a[k] * x[c];
          }
        }
      }
    } else {
      if (tr) {
        for (c = 0; c < ncol; ++c) {
          for (k = colind[c]; k < colind[c+1]; ++k) {
            r = row[k];
            if (r == c) {
              x[c] /= nz_a[k];
            } else {
              x[c] -= nz_a[k] * x[r];
            }
          }
        }
      } else {
        for (c = ncol; c-- > 0; ) {
          for (k = colind[c + 1]; k-- > colind[c]; ) {
            r = row[k];
            if (r == c) {
              x[r] /= nz_a[k];
            } else {
              x[r] -= nz_a[k] * x[c];
            }
          }
        }
      }
    }
    x += nrow;
  }
}

static const casadi_int casadi_s0[9] = 
  {3, 3, 0, 1, 2, 3, 0, 1,
  2};
static const casadi_int casadi_s1[3] = {15, 1, 1};
static const casadi_int casadi_s2[3] = {3, 1, 1};
static const casadi_int casadi_s3[3] = {0, 1, 1};

static const casadi_real casadi_c0[3] = {0., 0., -9.8100000000000005e+00};
static const casadi_real casadi_c1[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};
static const casadi_real casadi_c2[3] = {0., 0., -20.};

/* rocket_expl_ode_fun:(i0[15],i1[3],i2[0])->(o0[15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, *w02=w+6, w03, *w04=w+10, *w05=w+13, *w06=w+16, *w07=w+19, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, *w21=w+36, *w22=w+39;
  casadi_real *w23=w+42, *w24=w+45, *w25=w+54, *w26=w+63, *w27=w+67, *w28=w+71, *w29=w+75, *w30=w+79, *w31=w+83, *w32=w+99, *w33=w+115, *w34=w+118;
  const casadi_real *cs, *ct, *wr25;
  /* #0: @0 = input[0][5] */
  w00 = arg[0] ? arg[0][14] : 0;
  /* #1: @1 = -0.000339789 */
  w01 = -3.3978933061501872e-04;
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 3, w02);
  /* #3: @3 = ||@2||_F */
  w03 = casadi_norm_2(3, w02);
  /* #4: @1 = (@1*@3) */
  w01 *= w03;
  /* #5: @4 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+4 : 0, 3, w04);
  /* #6: @5 = [0, 0, -9.81] */
  casadi_copy(casadi_c0, 3, w05);
  /* #7: @6 = zeros(3x1) */
  casadi_clear(w06, 3);
  /* #8: @3 = 1 */
  w03 = 1.;
  /* #9: @7 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 4, w07);
  /* #10: @8 = @7[2] */
  for (rr=(&w08), cs=w07+2; cs!=w07+3; cs+=1) *rr++ = *cs;
  /* #11: @9 = sq(@8) */
  w09 = casadi_sq( w08 );
  /* #12: @10 = @7[3] */
  for (rr=(&w10), cs=w07+3; cs!=w07+4; cs+=1) *rr++ = *cs;
  /* #13: @11 = sq(@10) */
  w11 = casadi_sq( w10 );
  /* #14: @12 = (@9+@11) */
  w12  = (w09+w11);
  /* #15: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #16: @12 = (@3-@12) */
  w12  = (w03-w12);
  /* #17: @13 = @7[1] */
  for (rr=(&w13), cs=w07+1; cs!=w07+2; cs+=1) *rr++ = *cs;
  /* #18: @14 = (@13*@8) */
  w14  = (w13*w08);
  /* #19: @15 = @7[0] */
  for (rr=(&w15), cs=w07+0; cs!=w07+1; cs+=1) *rr++ = *cs;
  /* #20: @16 = (@15*@10) */
  w16  = (w15*w10);
  /* #21: @17 = (@14-@16) */
  w17  = (w14-w16);
  /* #22: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #23: @18 = (@13*@10) */
  w18  = (w13*w10);
  /* #24: @19 = (@15*@8) */
  w19  = (w15*w08);
  /* #25: @20 = (@18+@19) */
  w20  = (w18+w19);
  /* #26: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #27: @21 = horzcat(@12, @17, @20) */
  rr=w21;
  *rr++ = w12;
  *rr++ = w17;
  *rr++ = w20;
  /* #28: @21 = @21' */
  /* #29: @14 = (@14+@16) */
  w14 += w16;
  /* #30: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #31: @16 = sq(@13) */
  w16 = casadi_sq( w13 );
  /* #32: @11 = (@16+@11) */
  w11  = (w16+w11);
  /* #33: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #34: @11 = (@3-@11) */
  w11  = (w03-w11);
  /* #35: @8 = (@8*@10) */
  w08 *= w10;
  /* #36: @15 = (@15*@13) */
  w15 *= w13;
  /* #37: @13 = (@8-@15) */
  w13  = (w08-w15);
  /* #38: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #39: @22 = horzcat(@14, @11, @13) */
  rr=w22;
  *rr++ = w14;
  *rr++ = w11;
  *rr++ = w13;
  /* #40: @22 = @22' */
  /* #41: @18 = (@18-@19) */
  w18 -= w19;
  /* #42: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #43: @8 = (@8+@15) */
  w08 += w15;
  /* #44: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #45: @16 = (@16+@9) */
  w16 += w09;
  /* #46: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #47: @3 = (@3-@16) */
  w03 -= w16;
  /* #48: @23 = horzcat(@18, @8, @3) */
  rr=w23;
  *rr++ = w18;
  *rr++ = w08;
  *rr++ = w03;
  /* #49: @23 = @23' */
  /* #50: @24 = horzcat(@21, @22, @23) */
  rr=w24;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  /* #51: @25 = @24' */
  for (i=0, rr=w25, cs=w24; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #52: @18 = input[0][0] */
  w18 = arg[0] ? arg[0][0] : 0;
  /* #53: @25 = (@25/@18) */
  for (i=0, rr=w25; i<9; ++i) (*rr++) /= w18;
  /* #54: @21 = mac(@25,@2,@6) */
  casadi_copy(w06, 3, w21);
  for (i=0, rr=w21; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w25+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #55: @5 = (@5+@21) */
  for (i=0, rr=w05, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #56: @26 = zeros(4x1) */
  casadi_clear(w26, 4);
  /* #57: @8 = 0.5 */
  w08 = 5.0000000000000000e-01;
  /* #58: @3 = 0 */
  w03 = 0.;
  /* #59: @21 = input[0][4] */
  casadi_copy(arg[0] ? arg[0]+11 : 0, 3, w21);
  /* #60: @16 = @21[0] */
  for (rr=(&w16), cs=w21+0; cs!=w21+1; cs+=1) *rr++ = *cs;
  /* #61: @9 = (-@16) */
  w09 = (- w16 );
  /* #62: @15 = @21[1] */
  for (rr=(&w15), cs=w21+1; cs!=w21+2; cs+=1) *rr++ = *cs;
  /* #63: @19 = (-@15) */
  w19 = (- w15 );
  /* #64: @14 = @21[2] */
  for (rr=(&w14), cs=w21+2; cs!=w21+3; cs+=1) *rr++ = *cs;
  /* #65: @11 = (-@14) */
  w11 = (- w14 );
  /* #66: @27 = horzcat(@3, @9, @19, @11) */
  rr=w27;
  *rr++ = w03;
  *rr++ = w09;
  *rr++ = w19;
  *rr++ = w11;
  /* #67: @27 = @27' */
  /* #68: @28 = horzcat(@16, @3, @14, @19) */
  rr=w28;
  *rr++ = w16;
  *rr++ = w03;
  *rr++ = w14;
  *rr++ = w19;
  /* #69: @28 = @28' */
  /* #70: @29 = horzcat(@15, @11, @3, @16) */
  rr=w29;
  *rr++ = w15;
  *rr++ = w11;
  *rr++ = w03;
  *rr++ = w16;
  /* #71: @29 = @29' */
  /* #72: @30 = horzcat(@14, @15, @9, @3) */
  rr=w30;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w09;
  *rr++ = w03;
  /* #73: @30 = @30' */
  /* #74: @31 = horzcat(@27, @28, @29, @30) */
  rr=w31;
  for (i=0, cs=w27; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  /* #75: @32 = @31' */
  for (i=0, rr=w32, cs=w31; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #76: @32 = (@8*@32) */
  for (i=0, rr=w32, cs=w32; i<16; ++i) (*rr++)  = (w08*(*cs++));
  /* #77: @26 = mac(@32,@7,@26) */
  for (i=0, rr=w26; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w32+j, ct=w07+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #78: @25 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr25 = casadi_c1;
  /* #79: @22 = all_1e-05(3x3,3nz) */
  casadi_fill(w22, 3, 1.0000000000000001e-05);
  /* #80: @9 = 20.25 */
  w09 = 2.0250000000000000e+01;
  /* #81: @11 = 0.25 */
  w11 = 2.5000000000000000e-01;
  /* #82: @11 = (@11*@18) */
  w11 *= w18;
  /* #83: @11 = (@9*@11) */
  w11  = (w09*w11);
  /* #84: @19 = 2500 */
  w19 = 2500.;
  /* #85: @13 = 0.0833333 */
  w13 = 8.3333333333333329e-02;
  /* #86: @13 = (@13*@18) */
  w13 *= w18;
  /* #87: @19 = (@19*@13) */
  w19 *= w13;
  /* #88: @11 = (@11+@19) */
  w11 += w19;
  /* #89: @8 = (@8*@18) */
  w08 *= w18;
  /* #90: @9 = (@9*@8) */
  w09 *= w08;
  /* #91: @23 = vertcat(@11, @11, @9) */
  rr=w23;
  *rr++ = w11;
  *rr++ = w11;
  *rr++ = w09;
  /* #92: @33 = sparsity_cast(@23) */
  casadi_copy(w23, 3, w33);
  /* #93: @22 = (@22+@33) */
  for (i=0, rr=w22, cs=w33; i<3; ++i) (*rr++) += (*cs++);
  /* #94: @25 = (@22\@25) */
  casadi_copy(wr25, 9, w25);
  casadi_triusolve(casadi_s0, w22, w25, 0, 0, 3);
  /* #95: @22 = [0, 0, -20] */
  casadi_copy(casadi_c2, 3, w22);
  /* #96: @11 = @22[1] */
  for (rr=(&w11), cs=w22+1; cs!=w22+2; cs+=1) *rr++ = *cs;
  /* #97: @9 = @2[2] */
  for (rr=(&w09), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #98: @8 = (@11*@9) */
  w08  = (w11*w09);
  /* #99: @18 = @22[2] */
  for (rr=(&w18), cs=w22+2; cs!=w22+3; cs+=1) *rr++ = *cs;
  /* #100: @19 = @2[1] */
  for (rr=(&w19), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #101: @13 = (@18*@19) */
  w13  = (w18*w19);
  /* #102: @8 = (@8-@13) */
  w08 -= w13;
  /* #103: @13 = @2[0] */
  for (rr=(&w13), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #104: @18 = (@18*@13) */
  w18 *= w13;
  /* #105: @10 = @22[0] */
  for (rr=(&w10), cs=w22+0; cs!=w22+1; cs+=1) *rr++ = *cs;
  /* #106: @9 = (@10*@9) */
  w09  = (w10*w09);
  /* #107: @18 = (@18-@9) */
  w18 -= w09;
  /* #108: @10 = (@10*@19) */
  w10 *= w19;
  /* #109: @11 = (@11*@13) */
  w11 *= w13;
  /* #110: @10 = (@10-@11) */
  w10 -= w11;
  /* #111: @22 = vertcat(@8, @18, @10) */
  rr=w22;
  *rr++ = w08;
  *rr++ = w18;
  *rr++ = w10;
  /* #112: @23 = (@23*@21) */
  for (i=0, rr=w23, cs=w21; i<3; ++i) (*rr++) *= (*cs++);
  /* #113: @8 = @23[2] */
  for (rr=(&w08), cs=w23+2; cs!=w23+3; cs+=1) *rr++ = *cs;
  /* #114: @18 = (@15*@8) */
  w18  = (w15*w08);
  /* #115: @10 = @23[1] */
  for (rr=(&w10), cs=w23+1; cs!=w23+2; cs+=1) *rr++ = *cs;
  /* #116: @11 = (@14*@10) */
  w11  = (w14*w10);
  /* #117: @18 = (@18-@11) */
  w18 -= w11;
  /* #118: @11 = @23[0] */
  for (rr=(&w11), cs=w23+0; cs!=w23+1; cs+=1) *rr++ = *cs;
  /* #119: @14 = (@14*@11) */
  w14 *= w11;
  /* #120: @8 = (@16*@8) */
  w08  = (w16*w08);
  /* #121: @14 = (@14-@8) */
  w14 -= w08;
  /* #122: @16 = (@16*@10) */
  w16 *= w10;
  /* #123: @15 = (@15*@11) */
  w15 *= w11;
  /* #124: @16 = (@16-@15) */
  w16 -= w15;
  /* #125: @23 = vertcat(@18, @14, @16) */
  rr=w23;
  *rr++ = w18;
  *rr++ = w14;
  *rr++ = w16;
  /* #126: @22 = (@22-@23) */
  for (i=0, rr=w22, cs=w23; i<3; ++i) (*rr++) -= (*cs++);
  /* #127: @6 = mac(@25,@22,@6) */
  for (i=0, rr=w06; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w25+j, ct=w22+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #128: @34 = vertcat(@1, @4, @5, @26, @6) */
  rr=w34;
  *rr++ = w01;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w05; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w06; i<3; ++i) *rr++ = *cs++;
  /* #129: @34 = (@0*@34) */
  for (i=0, rr=w34, cs=w34; i<14; ++i) (*rr++)  = (w00*(*cs++));
  /* #130: output[0][0] = @34 */
  casadi_copy(w34, 14, res[0]);
  /* #131: output[0][1] = @3 */
  if (res[0]) res[0][14] = w03;
  return 0;
}

CASADI_SYMBOL_EXPORT int rocket_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rocket_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rocket_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rocket_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rocket_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rocket_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rocket_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void rocket_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rocket_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int rocket_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real rocket_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rocket_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rocket_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rocket_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rocket_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rocket_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 132;
  return 0;
}

CASADI_SYMBOL_EXPORT int rocket_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 132*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
