/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) rocket_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_triusolve CASADI_PREFIX(triusolve)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_triusolve(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x, int tr, int unity,
    casadi_int nrhs) {
  casadi_int nrow, ncol, r, c, k, rhs;
  const casadi_int *colind, *row;
  nrow = sp_a[0];
  ncol = sp_a[1];
  colind = sp_a + 2;
  row = colind + ncol + 1;
  for (rhs = 0; rhs < nrhs; ++rhs) {
    if (unity) {
      if (tr) {
        for (c = 0; c < ncol; ++c) {
          for (k = colind[c]; k < colind[c+1]; ++k) {
            x[c] += nz_a[k] * x[row[k]];
          }
        }
      } else {
        for (c = ncol; c-- > 0; ) {
          for (k = colind[c + 1]; k-- > colind[c]; ) {
            x[row[k]] += nz_a[k] * x[c];
          }
        }
      }
    } else {
      if (tr) {
        for (c = 0; c < ncol; ++c) {
          for (k = colind[c]; k < colind[c+1]; ++k) {
            r = row[k];
            if (r == c) {
              x[c] /= nz_a[k];
            } else {
              x[c] -= nz_a[k] * x[r];
            }
          }
        }
      } else {
        for (c = ncol; c-- > 0; ) {
          for (k = colind[c + 1]; k-- > colind[c]; ) {
            r = row[k];
            if (r == c) {
              x[r] /= nz_a[k];
            } else {
              x[r] -= nz_a[k] * x[c];
            }
          }
        }
      }
    }
    x += nrow;
  }
}

static const casadi_int casadi_s0[9] = 
  {3, 3, 0, 1, 2, 3, 0, 1,
  2};
static const casadi_int casadi_s1[3] = {14, 1, 1};
static const casadi_int casadi_s2[3] = {3, 1, 1};
static const casadi_int casadi_s3[3] = {0, 1, 1};

static const casadi_real casadi_c0[3] = {0., 0., -9.8100000000000005e+00};
static const casadi_real casadi_c1[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};
static const casadi_real casadi_c2[3] = {0., 0., -20.};

/* rocket_expl_ode_fun:(i0[14],i1[3],i2[0])->(o0[14]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+5, w02, *w03=w+9, *w04=w+12, *w05=w+15, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, *w18=w+31, *w19=w+34, *w20=w+37, *w21=w+40, *w22=w+49;
  casadi_real *w23=w+58, *w24=w+62, *w25=w+66, *w26=w+70, *w27=w+74, *w28=w+78, *w29=w+94;
  const casadi_real *cs, *ct, *wr22;
  /* #0: @0 = -0.000339789 */
  w00 = -3.3978933061501872e-04;
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 3, w01);
  /* #2: @2 = ||@1||_F */
  w02 = casadi_norm_2(3, w01);
  /* #3: @0 = (@0*@2) */
  w00 *= w02;
  /* #4: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #5: @3 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+4 : 0, 3, w03);
  /* #6: output[0][1] = @3 */
  if (res[0]) casadi_copy(w03, 3, res[0]+1);
  /* #7: @3 = [0, 0, -9.81] */
  casadi_copy(casadi_c0, 3, w03);
  /* #8: @4 = zeros(3x1) */
  casadi_clear(w04, 3);
  /* #9: @0 = 1 */
  w00 = 1.;
  /* #10: @5 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 4, w05);
  /* #11: @2 = @5[2] */
  for (rr=(&w02), cs=w05+2; cs!=w05+3; cs+=1) *rr++ = *cs;
  /* #12: @6 = sq(@2) */
  w06 = casadi_sq( w02 );
  /* #13: @7 = @5[3] */
  for (rr=(&w07), cs=w05+3; cs!=w05+4; cs+=1) *rr++ = *cs;
  /* #14: @8 = sq(@7) */
  w08 = casadi_sq( w07 );
  /* #15: @9 = (@6+@8) */
  w09  = (w06+w08);
  /* #16: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #17: @9 = (@0-@9) */
  w09  = (w00-w09);
  /* #18: @10 = @5[1] */
  for (rr=(&w10), cs=w05+1; cs!=w05+2; cs+=1) *rr++ = *cs;
  /* #19: @11 = (@10*@2) */
  w11  = (w10*w02);
  /* #20: @12 = @5[0] */
  for (rr=(&w12), cs=w05+0; cs!=w05+1; cs+=1) *rr++ = *cs;
  /* #21: @13 = (@12*@7) */
  w13  = (w12*w07);
  /* #22: @14 = (@11-@13) */
  w14  = (w11-w13);
  /* #23: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #24: @15 = (@10*@7) */
  w15  = (w10*w07);
  /* #25: @16 = (@12*@2) */
  w16  = (w12*w02);
  /* #26: @17 = (@15+@16) */
  w17  = (w15+w16);
  /* #27: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #28: @18 = horzcat(@9, @14, @17) */
  rr=w18;
  *rr++ = w09;
  *rr++ = w14;
  *rr++ = w17;
  /* #29: @18 = @18' */
  /* #30: @11 = (@11+@13) */
  w11 += w13;
  /* #31: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #32: @13 = sq(@10) */
  w13 = casadi_sq( w10 );
  /* #33: @8 = (@13+@8) */
  w08  = (w13+w08);
  /* #34: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #35: @8 = (@0-@8) */
  w08  = (w00-w08);
  /* #36: @2 = (@2*@7) */
  w02 *= w07;
  /* #37: @12 = (@12*@10) */
  w12 *= w10;
  /* #38: @10 = (@2-@12) */
  w10  = (w02-w12);
  /* #39: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #40: @19 = horzcat(@11, @8, @10) */
  rr=w19;
  *rr++ = w11;
  *rr++ = w08;
  *rr++ = w10;
  /* #41: @19 = @19' */
  /* #42: @15 = (@15-@16) */
  w15 -= w16;
  /* #43: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #44: @2 = (@2+@12) */
  w02 += w12;
  /* #45: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #46: @13 = (@13+@6) */
  w13 += w06;
  /* #47: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #48: @0 = (@0-@13) */
  w00 -= w13;
  /* #49: @20 = horzcat(@15, @2, @0) */
  rr=w20;
  *rr++ = w15;
  *rr++ = w02;
  *rr++ = w00;
  /* #50: @20 = @20' */
  /* #51: @21 = horzcat(@18, @19, @20) */
  rr=w21;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  /* #52: @22 = @21' */
  for (i=0, rr=w22, cs=w21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #53: @15 = input[0][0] */
  w15 = arg[0] ? arg[0][0] : 0;
  /* #54: @22 = (@22/@15) */
  for (i=0, rr=w22; i<9; ++i) (*rr++) /= w15;
  /* #55: @18 = mac(@22,@1,@4) */
  casadi_copy(w04, 3, w18);
  for (i=0, rr=w18; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w22+j, ct=w01+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #56: @3 = (@3+@18) */
  for (i=0, rr=w03, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #57: output[0][2] = @3 */
  if (res[0]) casadi_copy(w03, 3, res[0]+4);
  /* #58: @23 = zeros(4x1) */
  casadi_clear(w23, 4);
  /* #59: @2 = 0.5 */
  w02 = 5.0000000000000000e-01;
  /* #60: @0 = 0 */
  w00 = 0.;
  /* #61: @3 = input[0][4] */
  casadi_copy(arg[0] ? arg[0]+11 : 0, 3, w03);
  /* #62: @13 = @3[0] */
  for (rr=(&w13), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #63: @6 = (-@13) */
  w06 = (- w13 );
  /* #64: @12 = @3[1] */
  for (rr=(&w12), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #65: @16 = (-@12) */
  w16 = (- w12 );
  /* #66: @11 = @3[2] */
  for (rr=(&w11), cs=w03+2; cs!=w03+3; cs+=1) *rr++ = *cs;
  /* #67: @8 = (-@11) */
  w08 = (- w11 );
  /* #68: @24 = horzcat(@0, @6, @16, @8) */
  rr=w24;
  *rr++ = w00;
  *rr++ = w06;
  *rr++ = w16;
  *rr++ = w08;
  /* #69: @24 = @24' */
  /* #70: @25 = horzcat(@13, @0, @11, @16) */
  rr=w25;
  *rr++ = w13;
  *rr++ = w00;
  *rr++ = w11;
  *rr++ = w16;
  /* #71: @25 = @25' */
  /* #72: @26 = horzcat(@12, @8, @0, @13) */
  rr=w26;
  *rr++ = w12;
  *rr++ = w08;
  *rr++ = w00;
  *rr++ = w13;
  /* #73: @26 = @26' */
  /* #74: @27 = horzcat(@11, @12, @6, @0) */
  rr=w27;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w06;
  *rr++ = w00;
  /* #75: @27 = @27' */
  /* #76: @28 = horzcat(@24, @25, @26, @27) */
  rr=w28;
  for (i=0, cs=w24; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<4; ++i) *rr++ = *cs++;
  /* #77: @29 = @28' */
  for (i=0, rr=w29, cs=w28; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #78: @29 = (@2*@29) */
  for (i=0, rr=w29, cs=w29; i<16; ++i) (*rr++)  = (w02*(*cs++));
  /* #79: @23 = mac(@29,@5,@23) */
  for (i=0, rr=w23; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w29+j, ct=w05+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #80: output[0][3] = @23 */
  if (res[0]) casadi_copy(w23, 4, res[0]+7);
  /* #81: @22 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr22 = casadi_c1;
  /* #82: @6 = 20.25 */
  w06 = 2.0250000000000000e+01;
  /* #83: @0 = 0.25 */
  w00 = 2.5000000000000000e-01;
  /* #84: @0 = (@0*@15) */
  w00 *= w15;
  /* #85: @0 = (@6*@0) */
  w00  = (w06*w00);
  /* #86: @8 = 2500 */
  w08 = 2500.;
  /* #87: @16 = 0.0833333 */
  w16 = 8.3333333333333329e-02;
  /* #88: @16 = (@16*@15) */
  w16 *= w15;
  /* #89: @8 = (@8*@16) */
  w08 *= w16;
  /* #90: @0 = (@0+@8) */
  w00 += w08;
  /* #91: @2 = (@2*@15) */
  w02 *= w15;
  /* #92: @6 = (@6*@2) */
  w06 *= w02;
  /* #93: @18 = vertcat(@0, @0, @6) */
  rr=w18;
  *rr++ = w00;
  *rr++ = w00;
  *rr++ = w06;
  /* #94: @19 = sparsity_cast(@18) */
  casadi_copy(w18, 3, w19);
  /* #95: @22 = (@19\@22) */
  casadi_copy(wr22, 9, w22);
  casadi_triusolve(casadi_s0, w19, w22, 0, 0, 3);
  /* #96: @19 = [0, 0, -20] */
  casadi_copy(casadi_c2, 3, w19);
  /* #97: @0 = @19[1] */
  for (rr=(&w00), cs=w19+1; cs!=w19+2; cs+=1) *rr++ = *cs;
  /* #98: @6 = @1[2] */
  for (rr=(&w06), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #99: @2 = (@0*@6) */
  w02  = (w00*w06);
  /* #100: @15 = @19[2] */
  for (rr=(&w15), cs=w19+2; cs!=w19+3; cs+=1) *rr++ = *cs;
  /* #101: @8 = @1[1] */
  for (rr=(&w08), cs=w01+1; cs!=w01+2; cs+=1) *rr++ = *cs;
  /* #102: @16 = (@15*@8) */
  w16  = (w15*w08);
  /* #103: @2 = (@2-@16) */
  w02 -= w16;
  /* #104: @16 = @1[0] */
  for (rr=(&w16), cs=w01+0; cs!=w01+1; cs+=1) *rr++ = *cs;
  /* #105: @15 = (@15*@16) */
  w15 *= w16;
  /* #106: @10 = @19[0] */
  for (rr=(&w10), cs=w19+0; cs!=w19+1; cs+=1) *rr++ = *cs;
  /* #107: @6 = (@10*@6) */
  w06  = (w10*w06);
  /* #108: @15 = (@15-@6) */
  w15 -= w06;
  /* #109: @10 = (@10*@8) */
  w10 *= w08;
  /* #110: @0 = (@0*@16) */
  w00 *= w16;
  /* #111: @10 = (@10-@0) */
  w10 -= w00;
  /* #112: @19 = vertcat(@2, @15, @10) */
  rr=w19;
  *rr++ = w02;
  *rr++ = w15;
  *rr++ = w10;
  /* #113: @18 = (@18*@3) */
  for (i=0, rr=w18, cs=w03; i<3; ++i) (*rr++) *= (*cs++);
  /* #114: @2 = @18[2] */
  for (rr=(&w02), cs=w18+2; cs!=w18+3; cs+=1) *rr++ = *cs;
  /* #115: @15 = (@12*@2) */
  w15  = (w12*w02);
  /* #116: @10 = @18[1] */
  for (rr=(&w10), cs=w18+1; cs!=w18+2; cs+=1) *rr++ = *cs;
  /* #117: @0 = (@11*@10) */
  w00  = (w11*w10);
  /* #118: @15 = (@15-@0) */
  w15 -= w00;
  /* #119: @0 = @18[0] */
  for (rr=(&w00), cs=w18+0; cs!=w18+1; cs+=1) *rr++ = *cs;
  /* #120: @11 = (@11*@0) */
  w11 *= w00;
  /* #121: @2 = (@13*@2) */
  w02  = (w13*w02);
  /* #122: @11 = (@11-@2) */
  w11 -= w02;
  /* #123: @13 = (@13*@10) */
  w13 *= w10;
  /* #124: @12 = (@12*@0) */
  w12 *= w00;
  /* #125: @13 = (@13-@12) */
  w13 -= w12;
  /* #126: @18 = vertcat(@15, @11, @13) */
  rr=w18;
  *rr++ = w15;
  *rr++ = w11;
  *rr++ = w13;
  /* #127: @19 = (@19-@18) */
  for (i=0, rr=w19, cs=w18; i<3; ++i) (*rr++) -= (*cs++);
  /* #128: @4 = mac(@22,@19,@4) */
  for (i=0, rr=w04; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w22+j, ct=w19+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #129: output[0][4] = @4 */
  if (res[0]) casadi_copy(w04, 3, res[0]+11);
  return 0;
}

CASADI_SYMBOL_EXPORT int rocket_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rocket_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rocket_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rocket_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rocket_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rocket_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rocket_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void rocket_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rocket_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int rocket_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real rocket_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rocket_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rocket_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rocket_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rocket_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rocket_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 110;
  return 0;
}

CASADI_SYMBOL_EXPORT int rocket_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 110*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
