/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) rocket_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_triusolve CASADI_PREFIX(triusolve)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_triusolve(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x, int tr, int unity,
    casadi_int nrhs) {
  casadi_int nrow, ncol, r, c, k, rhs;
  const casadi_int *colind, *row;
  nrow = sp_a[0];
  ncol = sp_a[1];
  colind = sp_a + 2;
  row = colind + ncol + 1;
  for (rhs = 0; rhs < nrhs; ++rhs) {
    if (unity) {
      if (tr) {
        for (c = 0; c < ncol; ++c) {
          for (k = colind[c]; k < colind[c+1]; ++k) {
            x[c] += nz_a[k] * x[row[k]];
          }
        }
      } else {
        for (c = ncol; c-- > 0; ) {
          for (k = colind[c + 1]; k-- > colind[c]; ) {
            x[row[k]] += nz_a[k] * x[c];
          }
        }
      }
    } else {
      if (tr) {
        for (c = 0; c < ncol; ++c) {
          for (k = colind[c]; k < colind[c+1]; ++k) {
            r = row[k];
            if (r == c) {
              x[c] /= nz_a[k];
            } else {
              x[c] -= nz_a[k] * x[r];
            }
          }
        }
      } else {
        for (c = ncol; c-- > 0; ) {
          for (k = colind[c + 1]; k-- > colind[c]; ) {
            r = row[k];
            if (r == c) {
              x[r] /= nz_a[k];
            } else {
              x[r] -= nz_a[k] * x[c];
            }
          }
        }
      }
    }
    x += nrow;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

static const casadi_int casadi_s0[9] = 
  {3, 3, 0, 1, 2, 3, 0, 1,
  2};
static const casadi_int casadi_s1[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[3] = {14, 1, 1};
static const casadi_int casadi_s3[3] = {3, 1, 1};
static const casadi_int casadi_s4[3] = {0, 1, 1};
static const casadi_int casadi_s5[18] = 
  {17, 1, 0, 14, 0, 4, 5, 6,
  7, 8, 9, 10, 11, 12, 13, 14,
  15, 16};

static const casadi_real casadi_c0[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};
static const casadi_real casadi_c1[3] = {0., 0., -20.};

static const casadi_real casadi_zeros[14] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0.};

/* rocket_expl_vde_adj:(i0[14],i1[14],i2[3],i3[0])->(o0[17x1,14nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, *w02=w+6, *w03=w+9, w04, *w05=w+13, w06, w07, w08, w09, w10;
  casadi_real w11, *w12=w+28, *w13=w+31, *w14=w+34, *w16=w+57, *w18=w+63, *w20=w+70, *w21=w+73, w22, w23, w24, w25;
  casadi_real w26, w27, *w28=w+82, *w29=w+85, *w30=w+88, *w31=w+91, w32, w33, w34, w35, w36, w37;
  casadi_real w38, w39, *w40=w+102, *w41=w+111, w42, w43, w44, w45, w46, w47, w48, *w49=w+122;
  casadi_real *w50=w+126, *w51=w+130, *w52=w+134, *w53=w+138, *w54=w+142, *w55=w+158;
  const casadi_real *cr, *cs, *ct, *wr05, *wr15, *wr16, *wr17, *wr18, *wr19;
  /* #0: @0 = 0.5 */
  w00 = 5.0000000000000000e-01;
  /* #1: @1 = 20.25 */
  w01 = 2.0250000000000000e+01;
  /* #2: @2 = input[0][4] */
  casadi_copy(arg[0] ? arg[0]+11 : 0, 3, w02);
  /* #3: @3 = zeros(3x1) */
  casadi_clear(w03, 3);
  /* #4: @4 = @2[2] */
  for (rr=(&w04), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #5: @5 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr05 = casadi_c0;
  /* #6: @6 = 0.25 */
  w06 = 2.5000000000000000e-01;
  /* #7: @7 = input[0][0] */
  w07 = arg[0] ? arg[0][0] : 0;
  /* #8: @8 = (@6*@7) */
  w08  = (w06*w07);
  /* #9: @8 = (@1*@8) */
  w08  = (w01*w08);
  /* #10: @9 = 2500 */
  w09 = 2500.;
  /* #11: @10 = 0.0833333 */
  w10 = 8.3333333333333329e-02;
  /* #12: @11 = (@10*@7) */
  w11  = (w10*w07);
  /* #13: @11 = (@9*@11) */
  w11  = (w09*w11);
  /* #14: @8 = (@8+@11) */
  w08 += w11;
  /* #15: @11 = (@0*@7) */
  w11  = (w00*w07);
  /* #16: @11 = (@1*@11) */
  w11  = (w01*w11);
  /* #17: @12 = vertcat(@8, @8, @11) */
  rr=w12;
  *rr++ = w08;
  *rr++ = w08;
  *rr++ = w11;
  /* #18: @13 = sparsity_cast(@12) */
  casadi_copy(w12, 3, w13);
  /* #19: @5 = (@13\@5) */
  casadi_copy(wr05, 9, w05);
  casadi_triusolve(casadi_s0, w13, w05, 0, 0, 3);
  /* #20: @14 = @5' */
  for (i=0, rr=w14, cs=w05; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #21: @15 = input[1][0] */
  wr15 = arg[1] ? arg[1] : casadi_zeros;
  /* #22: {@8, @16, @17, @18, @19} = vertsplit(@15) */
  w08 = wr15[0];
  wr16 = wr15+1;
  wr17 = wr15+4;
  wr18 = wr15+7;
  wr19 = wr15+11;
  /* #23: @20 = mac(@14,@19,@3) */
  casadi_copy(w03, 3, w20);
  for (i=0, rr=w20; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w14+j, ct=wr19+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #24: @21 = (-@20) */
  for (i=0, rr=w21, cs=w20; i<3; ++i) *rr++ = (- *cs++ );
  /* #25: {@11, @22, @23} = vertsplit(@21) */
  w11 = w21[0];
  w22 = w21[1];
  w23 = w21[2];
  /* #26: @24 = (@4*@22) */
  w24  = (w04*w22);
  /* #27: @25 = @2[1] */
  for (rr=(&w25), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #28: @26 = (@25*@23) */
  w26  = (w25*w23);
  /* #29: @24 = (@24-@26) */
  w24 -= w26;
  /* #30: @21 = @3; (@21[0] += @24) */
  casadi_copy(w03, 3, w21);
  for (rr=w21+0, cs=(&w24); rr!=w21+1; rr+=1) *rr += *cs++;
  /* #31: @24 = @2[0] */
  for (rr=(&w24), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #32: @26 = (@24*@23) */
  w26  = (w24*w23);
  /* #33: @27 = (@4*@11) */
  w27  = (w04*w11);
  /* #34: @26 = (@26-@27) */
  w26 -= w27;
  /* #35: (@21[1] += @26) */
  for (rr=w21+1, cs=(&w26); rr!=w21+2; rr+=1) *rr += *cs++;
  /* #36: @26 = (@25*@11) */
  w26  = (w25*w11);
  /* #37: @27 = (@24*@22) */
  w27  = (w24*w22);
  /* #38: @26 = (@26-@27) */
  w26 -= w27;
  /* #39: (@21[2] += @26) */
  for (rr=w21+2, cs=(&w26); rr!=w21+3; rr+=1) *rr += *cs++;
  /* #40: @28 = (@2*@21) */
  for (i=0, rr=w28, cr=w02, cs=w21; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #41: @29 = zeros(3x3,3nz) */
  casadi_clear(w29, 3);
  /* #42: @5 = zeros(3x3) */
  casadi_clear(w05, 9);
  /* #43: @30 = [0, 0, -20] */
  casadi_copy(casadi_c1, 3, w30);
  /* #44: @26 = @30[1] */
  for (rr=(&w26), cs=w30+1; cs!=w30+2; cs+=1) *rr++ = *cs;
  /* #45: @31 = input[2][0] */
  casadi_copy(arg[2], 3, w31);
  /* #46: @27 = @31[2] */
  for (rr=(&w27), cs=w31+2; cs!=w31+3; cs+=1) *rr++ = *cs;
  /* #47: @32 = (@26*@27) */
  w32  = (w26*w27);
  /* #48: @33 = @30[2] */
  for (rr=(&w33), cs=w30+2; cs!=w30+3; cs+=1) *rr++ = *cs;
  /* #49: @34 = @31[1] */
  for (rr=(&w34), cs=w31+1; cs!=w31+2; cs+=1) *rr++ = *cs;
  /* #50: @35 = (@33*@34) */
  w35  = (w33*w34);
  /* #51: @32 = (@32-@35) */
  w32 -= w35;
  /* #52: @35 = @31[0] */
  for (rr=(&w35), cs=w31+0; cs!=w31+1; cs+=1) *rr++ = *cs;
  /* #53: @36 = (@33*@35) */
  w36  = (w33*w35);
  /* #54: @37 = @30[0] */
  for (rr=(&w37), cs=w30+0; cs!=w30+1; cs+=1) *rr++ = *cs;
  /* #55: @27 = (@37*@27) */
  w27  = (w37*w27);
  /* #56: @36 = (@36-@27) */
  w36 -= w27;
  /* #57: @34 = (@37*@34) */
  w34  = (w37*w34);
  /* #58: @35 = (@26*@35) */
  w35  = (w26*w35);
  /* #59: @34 = (@34-@35) */
  w34 -= w35;
  /* #60: @30 = vertcat(@32, @36, @34) */
  rr=w30;
  *rr++ = w32;
  *rr++ = w36;
  *rr++ = w34;
  /* #61: @2 = (@12*@2) */
  for (i=0, rr=w02, cr=w12, cs=w02; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #62: @32 = @2[2] */
  for (rr=(&w32), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #63: @36 = (@25*@32) */
  w36  = (w25*w32);
  /* #64: @34 = @2[1] */
  for (rr=(&w34), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #65: @35 = (@4*@34) */
  w35  = (w04*w34);
  /* #66: @36 = (@36-@35) */
  w36 -= w35;
  /* #67: @35 = @2[0] */
  for (rr=(&w35), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #68: @27 = (@4*@35) */
  w27  = (w04*w35);
  /* #69: @38 = (@24*@32) */
  w38  = (w24*w32);
  /* #70: @27 = (@27-@38) */
  w27 -= w38;
  /* #71: @38 = (@24*@34) */
  w38  = (w24*w34);
  /* #72: @39 = (@25*@35) */
  w39  = (w25*w35);
  /* #73: @38 = (@38-@39) */
  w38 -= w39;
  /* #74: @2 = vertcat(@36, @27, @38) */
  rr=w02;
  *rr++ = w36;
  *rr++ = w27;
  *rr++ = w38;
  /* #75: @30 = (@30-@2) */
  for (i=0, rr=w30, cs=w02; i<3; ++i) (*rr++) -= (*cs++);
  /* #76: @30 = @30' */
  /* #77: @40 = mac(@19,@30,@5) */
  casadi_copy(w05, 9, w40);
  for (i=0, rr=w40; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr19+j, ct=w30+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #78: @40 = (@13'\@40) */
  casadi_triusolve(casadi_s0, w13, w40, 1, 0, 3);
  /* #79: @29 = mac(@40,@14,@29) */
  casadi_mtimes(w40, casadi_s1, w14, casadi_s1, w29, casadi_s0, w, 0);
  /* #80: @29 = (-@29) */
  for (i=0, rr=w29, cs=w29; i<3; ++i) *rr++ = (- *cs++ );
  /* #81: @29 = nonzeros(@29) */
  /* #82: @28 = (@28+@29) */
  for (i=0, rr=w28, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #83: {@36, @27, @38} = vertsplit(@28) */
  w36 = w28[0];
  w27 = w28[1];
  w38 = w28[2];
  /* #84: @38 = (@1*@38) */
  w38  = (w01*w38);
  /* #85: @38 = (@0*@38) */
  w38  = (w00*w38);
  /* #86: @39 = (@9*@27) */
  w39  = (w09*w27);
  /* #87: @39 = (@10*@39) */
  w39  = (w10*w39);
  /* #88: @38 = (@38+@39) */
  w38 += w39;
  /* #89: @27 = (@1*@27) */
  w27  = (w01*w27);
  /* #90: @27 = (@6*@27) */
  w27  = (w06*w27);
  /* #91: @38 = (@38+@27) */
  w38 += w27;
  /* #92: @9 = (@9*@36) */
  w09 *= w36;
  /* #93: @10 = (@10*@9) */
  w10 *= w09;
  /* #94: @38 = (@38+@10) */
  w38 += w10;
  /* #95: @1 = (@1*@36) */
  w01 *= w36;
  /* #96: @6 = (@6*@1) */
  w06 *= w01;
  /* #97: @38 = (@38+@6) */
  w38 += w06;
  /* #98: @6 = 1 */
  w06 = 1.;
  /* #99: @41 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 4, w41);
  /* #100: @1 = @41[2] */
  for (rr=(&w01), cs=w41+2; cs!=w41+3; cs+=1) *rr++ = *cs;
  /* #101: @36 = sq(@1) */
  w36 = casadi_sq( w01 );
  /* #102: @10 = @41[3] */
  for (rr=(&w10), cs=w41+3; cs!=w41+4; cs+=1) *rr++ = *cs;
  /* #103: @9 = sq(@10) */
  w09 = casadi_sq( w10 );
  /* #104: @27 = (@36+@9) */
  w27  = (w36+w09);
  /* #105: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #106: @27 = (@6-@27) */
  w27  = (w06-w27);
  /* #107: @39 = @41[1] */
  for (rr=(&w39), cs=w41+1; cs!=w41+2; cs+=1) *rr++ = *cs;
  /* #108: @42 = (@39*@1) */
  w42  = (w39*w01);
  /* #109: @43 = @41[0] */
  for (rr=(&w43), cs=w41+0; cs!=w41+1; cs+=1) *rr++ = *cs;
  /* #110: @44 = (@43*@10) */
  w44  = (w43*w10);
  /* #111: @45 = (@42-@44) */
  w45  = (w42-w44);
  /* #112: @45 = (2.*@45) */
  w45 = (2.* w45 );
  /* #113: @46 = (@39*@10) */
  w46  = (w39*w10);
  /* #114: @47 = (@43*@1) */
  w47  = (w43*w01);
  /* #115: @48 = (@46+@47) */
  w48  = (w46+w47);
  /* #116: @48 = (2.*@48) */
  w48 = (2.* w48 );
  /* #117: @28 = horzcat(@27, @45, @48) */
  rr=w28;
  *rr++ = w27;
  *rr++ = w45;
  *rr++ = w48;
  /* #118: @28 = @28' */
  /* #119: @42 = (@42+@44) */
  w42 += w44;
  /* #120: @42 = (2.*@42) */
  w42 = (2.* w42 );
  /* #121: @44 = sq(@39) */
  w44 = casadi_sq( w39 );
  /* #122: @9 = (@44+@9) */
  w09  = (w44+w09);
  /* #123: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #124: @9 = (@6-@9) */
  w09  = (w06-w09);
  /* #125: @27 = (@1*@10) */
  w27  = (w01*w10);
  /* #126: @45 = (@43*@39) */
  w45  = (w43*w39);
  /* #127: @48 = (@27-@45) */
  w48  = (w27-w45);
  /* #128: @48 = (2.*@48) */
  w48 = (2.* w48 );
  /* #129: @29 = horzcat(@42, @9, @48) */
  rr=w29;
  *rr++ = w42;
  *rr++ = w09;
  *rr++ = w48;
  /* #130: @29 = @29' */
  /* #131: @46 = (@46-@47) */
  w46 -= w47;
  /* #132: @46 = (2.*@46) */
  w46 = (2.* w46 );
  /* #133: @27 = (@27+@45) */
  w27 += w45;
  /* #134: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #135: @44 = (@44+@36) */
  w44 += w36;
  /* #136: @44 = (2.*@44) */
  w44 = (2.* w44 );
  /* #137: @6 = (@6-@44) */
  w06 -= w44;
  /* #138: @13 = horzcat(@46, @27, @6) */
  rr=w13;
  *rr++ = w46;
  *rr++ = w27;
  *rr++ = w06;
  /* #139: @13 = @13' */
  /* #140: @40 = horzcat(@28, @29, @13) */
  rr=w40;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #141: @14 = @40' */
  for (i=0, rr=w14, cs=w40; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #142: @14 = (@14/@7) */
  for (i=0, rr=w14; i<9; ++i) (*rr++) /= w07;
  /* #143: @40 = (@14/@7) */
  for (i=0, rr=w40, cr=w14; i<9; ++i) (*rr++)  = ((*cr++)/w07);
  /* #144: @40 = (-@40) */
  for (i=0, rr=w40, cs=w40; i<9; ++i) *rr++ = (- *cs++ );
  /* #145: @28 = @31' */
  casadi_copy(w31, 3, w28);
  /* #146: @5 = mac(@17,@28,@5) */
  for (i=0, rr=w05; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr17+j, ct=w28+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #147: @46 = dot(@40, @5) */
  w46 = casadi_dot(9, w40, w05);
  /* #148: @38 = (@38+@46) */
  w38 += w46;
  /* #149: output[0][0] = @38 */
  if (res[0]) res[0][0] = w38;
  /* #150: output[0][1] = @16 */
  if (res[0]) casadi_copy(wr16, 3, res[0]+1);
  /* #151: @49 = zeros(4x1) */
  casadi_clear(w49, 4);
  /* #152: @38 = 0 */
  w38 = 0.;
  /* #153: @46 = (-@24) */
  w46 = (- w24 );
  /* #154: @27 = (-@25) */
  w27 = (- w25 );
  /* #155: @6 = (-@4) */
  w06 = (- w04 );
  /* #156: @50 = horzcat(@38, @46, @27, @6) */
  rr=w50;
  *rr++ = w38;
  *rr++ = w46;
  *rr++ = w27;
  *rr++ = w06;
  /* #157: @50 = @50' */
  /* #158: @51 = horzcat(@24, @38, @4, @27) */
  rr=w51;
  *rr++ = w24;
  *rr++ = w38;
  *rr++ = w04;
  *rr++ = w27;
  /* #159: @51 = @51' */
  /* #160: @52 = horzcat(@25, @6, @38, @24) */
  rr=w52;
  *rr++ = w25;
  *rr++ = w06;
  *rr++ = w38;
  *rr++ = w24;
  /* #161: @52 = @52' */
  /* #162: @53 = horzcat(@4, @25, @46, @38) */
  rr=w53;
  *rr++ = w04;
  *rr++ = w25;
  *rr++ = w46;
  *rr++ = w38;
  /* #163: @53 = @53' */
  /* #164: @54 = horzcat(@50, @51, @52, @53) */
  rr=w54;
  for (i=0, cs=w50; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w51; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w52; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w53; i<4; ++i) *rr++ = *cs++;
  /* #165: @55 = @54' */
  for (i=0, rr=w55, cs=w54; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #166: @55 = (@0*@55) */
  for (i=0, rr=w55, cs=w55; i<16; ++i) (*rr++)  = (w00*(*cs++));
  /* #167: @54 = @55' */
  for (i=0, rr=w54, cs=w55; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #168: @49 = mac(@54,@18,@49) */
  for (i=0, rr=w49; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w54+j, ct=wr18+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #169: @5 = (@5/@7) */
  for (i=0, rr=w05; i<9; ++i) (*rr++) /= w07;
  /* #170: @40 = @5' */
  for (i=0, rr=w40, cs=w05; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #171: {@16, @28, @29} = horzsplit(@40) */
  casadi_copy(w40, 3, w16);
  casadi_copy(w40+3, 3, w28);
  casadi_copy(w40+6, 3, w29);
  /* #172: @29 = @29' */
  /* #173: {@7, @4, @25} = horzsplit(@29) */
  w07 = w29[0];
  w04 = w29[1];
  w25 = w29[2];
  /* #174: @4 = (2.*@4) */
  w04 = (2.* w04 );
  /* #175: @46 = (@39*@4) */
  w46  = (w39*w04);
  /* #176: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #177: @38 = (@1*@7) */
  w38  = (w01*w07);
  /* #178: @46 = (@46-@38) */
  w46 -= w38;
  /* #179: @28 = @28' */
  /* #180: {@38, @6, @24} = horzsplit(@28) */
  w38 = w28[0];
  w06 = w28[1];
  w24 = w28[2];
  /* #181: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #182: @27 = (@39*@24) */
  w27  = (w39*w24);
  /* #183: @46 = (@46-@27) */
  w46 -= w27;
  /* #184: @38 = (2.*@38) */
  w38 = (2.* w38 );
  /* #185: @27 = (@10*@38) */
  w27  = (w10*w38);
  /* #186: @46 = (@46+@27) */
  w46 += w27;
  /* #187: @16 = @16' */
  /* #188: {@27, @44, @36} = horzsplit(@16) */
  w27 = w16[0];
  w44 = w16[1];
  w36 = w16[2];
  /* #189: @36 = (2.*@36) */
  w36 = (2.* w36 );
  /* #190: @45 = (@1*@36) */
  w45  = (w01*w36);
  /* #191: @46 = (@46+@45) */
  w46 += w45;
  /* #192: @44 = (2.*@44) */
  w44 = (2.* w44 );
  /* #193: @45 = (@10*@44) */
  w45  = (w10*w44);
  /* #194: @46 = (@46-@45) */
  w46 -= w45;
  /* #195: (@49[0] += @46) */
  for (rr=w49+0, cs=(&w46); rr!=w49+1; rr+=1) *rr += *cs++;
  /* #196: @46 = (2.*@39) */
  w46 = (2.* w39 );
  /* #197: @25 = (-@25) */
  w25 = (- w25 );
  /* #198: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #199: @45 = (@46*@25) */
  w45  = (w46*w25);
  /* #200: @47 = (@43*@4) */
  w47  = (w43*w04);
  /* #201: @45 = (@45+@47) */
  w45 += w47;
  /* #202: @47 = (@10*@7) */
  w47  = (w10*w07);
  /* #203: @45 = (@45+@47) */
  w45 += w47;
  /* #204: @47 = (@43*@24) */
  w47  = (w43*w24);
  /* #205: @45 = (@45-@47) */
  w45 -= w47;
  /* #206: @6 = (-@6) */
  w06 = (- w06 );
  /* #207: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #208: @46 = (@46*@6) */
  w46 *= w06;
  /* #209: @45 = (@45+@46) */
  w45 += w46;
  /* #210: @46 = (@1*@38) */
  w46  = (w01*w38);
  /* #211: @45 = (@45+@46) */
  w45 += w46;
  /* #212: @46 = (@10*@36) */
  w46  = (w10*w36);
  /* #213: @45 = (@45+@46) */
  w45 += w46;
  /* #214: @46 = (@1*@44) */
  w46  = (w01*w44);
  /* #215: @45 = (@45+@46) */
  w45 += w46;
  /* #216: (@49[1] += @45) */
  for (rr=w49+1, cs=(&w45); rr!=w49+2; rr+=1) *rr += *cs++;
  /* #217: @45 = (@1*@4) */
  w45  = (w01*w04);
  /* #218: @46 = (@39*@7) */
  w46  = (w39*w07);
  /* #219: @45 = (@45+@46) */
  w45 += w46;
  /* #220: @46 = (@1*@24) */
  w46  = (w01*w24);
  /* #221: @45 = (@45+@46) */
  w45 += w46;
  /* #222: @46 = (2.*@10) */
  w46 = (2.* w10 );
  /* #223: @6 = (@46*@6) */
  w06  = (w46*w06);
  /* #224: @45 = (@45+@6) */
  w45 += w06;
  /* #225: @6 = (@43*@38) */
  w06  = (w43*w38);
  /* #226: @45 = (@45+@6) */
  w45 += w06;
  /* #227: @6 = (@39*@36) */
  w06  = (w39*w36);
  /* #228: @45 = (@45+@6) */
  w45 += w06;
  /* #229: @6 = (@43*@44) */
  w06  = (w43*w44);
  /* #230: @45 = (@45-@6) */
  w45 -= w06;
  /* #231: @27 = (-@27) */
  w27 = (- w27 );
  /* #232: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #233: @46 = (@46*@27) */
  w46 *= w27;
  /* #234: @45 = (@45+@46) */
  w45 += w46;
  /* #235: (@49[3] += @45) */
  for (rr=w49+3, cs=(&w45); rr!=w49+4; rr+=1) *rr += *cs++;
  /* #236: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #237: @25 = (@1*@25) */
  w25  = (w01*w25);
  /* #238: @4 = (@10*@4) */
  w04  = (w10*w04);
  /* #239: @25 = (@25+@4) */
  w25 += w04;
  /* #240: @7 = (@43*@7) */
  w07  = (w43*w07);
  /* #241: @25 = (@25-@7) */
  w25 -= w07;
  /* #242: @10 = (@10*@24) */
  w10 *= w24;
  /* #243: @25 = (@25+@10) */
  w25 += w10;
  /* #244: @38 = (@39*@38) */
  w38  = (w39*w38);
  /* #245: @25 = (@25+@38) */
  w25 += w38;
  /* #246: @43 = (@43*@36) */
  w43 *= w36;
  /* #247: @25 = (@25+@43) */
  w25 += w43;
  /* #248: @39 = (@39*@44) */
  w39 *= w44;
  /* #249: @25 = (@25+@39) */
  w25 += w39;
  /* #250: @1 = (@1*@27) */
  w01 *= w27;
  /* #251: @25 = (@25+@1) */
  w25 += w01;
  /* #252: (@49[2] += @25) */
  for (rr=w49+2, cs=(&w25); rr!=w49+3; rr+=1) *rr += *cs++;
  /* #253: output[0][2] = @49 */
  if (res[0]) casadi_copy(w49, 4, res[0]+4);
  /* #254: @25 = (@34*@23) */
  w25  = (w34*w23);
  /* #255: @1 = (@32*@22) */
  w01  = (w32*w22);
  /* #256: @25 = (@25-@1) */
  w25 -= w01;
  /* #257: @16 = @3; (@16[0] += @25) */
  casadi_copy(w03, 3, w16);
  for (rr=w16+0, cs=(&w25); rr!=w16+1; rr+=1) *rr += *cs++;
  /* #258: @22 = (@35*@22) */
  w22  = (w35*w22);
  /* #259: @34 = (@34*@11) */
  w34 *= w11;
  /* #260: @22 = (@22-@34) */
  w22 -= w34;
  /* #261: (@16[2] += @22) */
  for (rr=w16+2, cs=(&w22); rr!=w16+3; rr+=1) *rr += *cs++;
  /* #262: @12 = (@12*@21) */
  for (i=0, rr=w12, cs=w21; i<3; ++i) (*rr++) *= (*cs++);
  /* #263: @16 = (@16+@12) */
  for (i=0, rr=w16, cs=w12; i<3; ++i) (*rr++) += (*cs++);
  /* #264: @32 = (@32*@11) */
  w32 *= w11;
  /* #265: @35 = (@35*@23) */
  w35 *= w23;
  /* #266: @32 = (@32-@35) */
  w32 -= w35;
  /* #267: (@16[1] += @32) */
  for (rr=w16+1, cs=(&w32); rr!=w16+2; rr+=1) *rr += *cs++;
  /* #268: @54 = zeros(4x4) */
  casadi_clear(w54, 16);
  /* #269: @41 = @41' */
  /* #270: @54 = mac(@18,@41,@54) */
  for (i=0, rr=w54; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=wr18+j, ct=w41+i*1; k<1; ++k) *rr += cs[k*4]**ct++;
  /* #271: @54 = (@0*@54) */
  for (i=0, rr=w54, cs=w54; i<16; ++i) (*rr++)  = (w00*(*cs++));
  /* #272: @55 = @54' */
  for (i=0, rr=w55, cs=w54; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #273: {@18, @41, @49, @50} = horzsplit(@55) */
  casadi_copy(w55, 4, w18);
  casadi_copy(w55+4, 4, w41);
  casadi_copy(w55+8, 4, w49);
  casadi_copy(w55+12, 4, w50);
  /* #274: @50 = @50' */
  /* #275: {@0, @32, @35, NULL} = horzsplit(@50) */
  w00 = w50[0];
  w32 = w50[1];
  w35 = w50[2];
  /* #276: @49 = @49' */
  /* #277: {@23, @11, NULL, @22} = horzsplit(@49) */
  w23 = w49[0];
  w11 = w49[1];
  w22 = w49[3];
  /* #278: @0 = (@0-@11) */
  w00 -= w11;
  /* #279: @41 = @41' */
  /* #280: {@11, NULL, @34, @25} = horzsplit(@41) */
  w11 = w41[0];
  w34 = w41[2];
  w25 = w41[3];
  /* #281: @0 = (@0+@34) */
  w00 += w34;
  /* #282: @18 = @18' */
  /* #283: {NULL, @34, @1, @27} = horzsplit(@18) */
  w34 = w18[1];
  w01 = w18[2];
  w27 = w18[3];
  /* #284: @0 = (@0-@27) */
  w00 -= w27;
  /* #285: (@16[2] += @0) */
  for (rr=w16+2, cs=(&w00); rr!=w16+3; rr+=1) *rr += *cs++;
  /* #286: @32 = (@32+@23) */
  w32 += w23;
  /* #287: @32 = (@32-@25) */
  w32 -= w25;
  /* #288: @32 = (@32-@1) */
  w32 -= w01;
  /* #289: (@16[1] += @32) */
  for (rr=w16+1, cs=(&w32); rr!=w16+2; rr+=1) *rr += *cs++;
  /* #290: @22 = (@22-@35) */
  w22 -= w35;
  /* #291: @22 = (@22+@11) */
  w22 += w11;
  /* #292: @22 = (@22-@34) */
  w22 -= w34;
  /* #293: (@16[0] += @22) */
  for (rr=w16+0, cs=(&w22); rr!=w16+1; rr+=1) *rr += *cs++;
  /* #294: output[0][3] = @16 */
  if (res[0]) casadi_copy(w16, 3, res[0]+8);
  /* #295: {@22, @34, @11} = vertsplit(@20) */
  w22 = w20[0];
  w34 = w20[1];
  w11 = w20[2];
  /* #296: @35 = (@33*@34) */
  w35  = (w33*w34);
  /* #297: @32 = (@26*@11) */
  w32  = (w26*w11);
  /* #298: @35 = (@35-@32) */
  w35 -= w32;
  /* #299: @20 = @3; (@20[0] += @35) */
  casadi_copy(w03, 3, w20);
  for (rr=w20+0, cs=(&w35); rr!=w20+1; rr+=1) *rr += *cs++;
  /* #300: @11 = (@37*@11) */
  w11  = (w37*w11);
  /* #301: @33 = (@33*@22) */
  w33 *= w22;
  /* #302: @11 = (@11-@33) */
  w11 -= w33;
  /* #303: (@20[1] += @11) */
  for (rr=w20+1, cs=(&w11); rr!=w20+2; rr+=1) *rr += *cs++;
  /* #304: @26 = (@26*@22) */
  w26 *= w22;
  /* #305: @37 = (@37*@34) */
  w37 *= w34;
  /* #306: @26 = (@26-@37) */
  w26 -= w37;
  /* #307: (@20[2] += @26) */
  for (rr=w20+2, cs=(&w26); rr!=w20+3; rr+=1) *rr += *cs++;
  /* #308: @40 = @14' */
  for (i=0, rr=w40, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #309: @3 = mac(@40,@17,@3) */
  for (i=0, rr=w03; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w40+j, ct=wr17+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #310: @20 = (@20+@3) */
  for (i=0, rr=w20, cs=w03; i<3; ++i) (*rr++) += (*cs++);
  /* #311: @26 = -0.000339789 */
  w26 = -3.3978933061501872e-04;
  /* #312: @26 = (@26*@8) */
  w26 *= w08;
  /* #313: @8 = ||@31||_F */
  w08 = casadi_norm_2(3, w31);
  /* #314: @26 = (@26/@8) */
  w26 /= w08;
  /* #315: @31 = (@26*@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) (*rr++)  = (w26*(*cs++));
  /* #316: @20 = (@20+@31) */
  for (i=0, rr=w20, cs=w31; i<3; ++i) (*rr++) += (*cs++);
  /* #317: output[0][4] = @20 */
  if (res[0]) casadi_copy(w20, 3, res[0]+11);
  return 0;
}

CASADI_SYMBOL_EXPORT int rocket_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rocket_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rocket_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rocket_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rocket_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rocket_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rocket_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void rocket_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rocket_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int rocket_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real rocket_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rocket_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rocket_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rocket_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rocket_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rocket_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 174;
  return 0;
}

CASADI_SYMBOL_EXPORT int rocket_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 6*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 174*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
