/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) rocket_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s1[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s2[4] = {0, 4, 7, 12};
static const casadi_int casadi_s3[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s4[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s5[4] = {1, 5, 8, 13};
static const casadi_int casadi_s6[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s7[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s8[5] = {2, 6, 9, 10, 14};
static const casadi_int casadi_s9[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s10[3] = {14, 1, 1};
static const casadi_int casadi_s11[3] = {3, 1, 1};
static const casadi_int casadi_s12[3] = {0, 1, 1};
static const casadi_int casadi_s13[3] = {5, 1, 1};
static const casadi_int casadi_s14[23] = 
  {17, 5, 0, 4, 7, 10, 12, 15,
  10, 11, 12, 13, 0, 1, 2, 0,
  1, 2, 12, 13, 14, 15, 16};
static const casadi_int casadi_s15[3] = {5, 0, 1};

static const casadi_real casadi_c0[3] = {0., 0., 1.};

/* rocket_constr_h_fun_jac_uxt_zt:(i0[14],i1[3],i2[0],i3[0])->(o0[5],o1[17x5,15nz],o2[5x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *w00=w+0, w01, w02, w03, *w04=w+7, *w05=w+10, w06, w07, w08, w09, w10;
  casadi_real *w11=w+18, *w12=w+21, *w13=w+36, w14, w15, w16, w17, *w19=w+50, *w20=w+54, *w21=w+58, w22, *w23=w+62;
  casadi_real *w24=w+67, *w25=w+69;
  const casadi_int *cii;
  const casadi_real *cs;
  /* #0: @0 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 4, w00);
  /* #1: @1 = ||@0||_F */
  w01 = casadi_norm_2(4, w00);
  /* #2: @2 = 1 */
  w02 = 1.;
  /* #3: @3 = (@1-@2) */
  w03  = (w01-w02);
  /* #4: output[0][0] = @3 */
  if (res[0]) res[0][0] = w03;
  /* #5: @4 = input[1][0] */
  casadi_copy(arg[1], 3, w04);
  /* #6: @3 = ||@4||_F */
  w03 = casadi_norm_2(3, w04);
  /* #7: output[0][1] = @3 */
  if (res[0]) res[0][1] = w03;
  /* #8: @5 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w05);
  /* #9: @6 = dot(@5, @4) */
  w06 = casadi_dot(3, w05, w04);
  /* #10: @6 = (@6/@3) */
  w06 /= w03;
  /* #11: output[0][2] = @6 */
  if (res[0]) res[0][2] = w06;
  /* #12: @7 = @0[2] */
  for (rr=(&w07), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #13: @8 = sq(@7) */
  w08 = casadi_sq( w07 );
  /* #14: @9 = @0[3] */
  for (rr=(&w09), cs=w00+3; cs!=w00+4; cs+=1) *rr++ = *cs;
  /* #15: @10 = sq(@9) */
  w10 = casadi_sq( w09 );
  /* #16: @8 = (@8+@10) */
  w08 += w10;
  /* #17: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #18: @2 = (@2-@8) */
  w02 -= w08;
  /* #19: output[0][3] = @2 */
  if (res[0]) res[0][3] = w02;
  /* #20: @11 = input[0][4] */
  casadi_copy(arg[0] ? arg[0]+11 : 0, 3, w11);
  /* #21: @2 = ||@11||_F */
  w02 = casadi_norm_2(3, w11);
  /* #22: output[0][4] = @2 */
  if (res[0]) res[0][4] = w02;
  /* #23: @12 = zeros(17x5,15nz) */
  casadi_clear(w12, 15);
  /* #24: @8 = project(@0) */
  casadi_sparsify(w00, (&w08), casadi_s0, 0);
  /* #25: @13 = ones(17x1,10nz) */
  casadi_fill(w13, 10, 1.);
  /* #26: {@10, NULL, NULL, NULL, @14, @15} = vertsplit(@13) */
  w10 = w13[0];
  w14 = w13[8];
  w15 = w13[9];
  /* #27: @16 = dot(@8, @14) */
  w16 = casadi_dot(1, (&w08), (&w14));
  /* #28: @16 = (@16/@1) */
  w16 /= w01;
  /* #29: @8 = project(@4) */
  casadi_sparsify(w04, (&w08), casadi_s1, 0);
  /* #30: @14 = dot(@8, @10) */
  w14 = casadi_dot(1, (&w08), (&w10));
  /* #31: @14 = (@14/@3) */
  w14 /= w03;
  /* #32: @8 = project(@5) */
  casadi_sparsify(w05, (&w08), casadi_s1, 0);
  /* #33: @17 = dot(@8, @10) */
  w17 = casadi_dot(1, (&w08), (&w10));
  /* #34: @17 = (@17/@3) */
  w17 /= w03;
  /* #35: @6 = (@6/@3) */
  w06 /= w03;
  /* #36: @8 = (@6*@14) */
  w08  = (w06*w14);
  /* #37: @17 = (@17-@8) */
  w17 -= w08;
  /* #38: @18 = 00 */
  /* #39: @8 = project(@11) */
  casadi_sparsify(w11, (&w08), casadi_s1, 0);
  /* #40: @10 = dot(@8, @15) */
  w10 = casadi_dot(1, (&w08), (&w15));
  /* #41: @10 = (@10/@2) */
  w10 /= w02;
  /* #42: @19 = vertcat(@16, @14, @17, @18, @10) */
  rr=w19;
  *rr++ = w16;
  *rr++ = w14;
  *rr++ = w17;
  *rr++ = w10;
  /* #43: @20 = @19[:4] */
  for (rr=w20, cs=w19+0; cs!=w19+4; cs+=1) *rr++ = *cs;
  /* #44: (@12[0, 4, 7, 12] = @20) */
  for (cii=casadi_s2, rr=w12, cs=w20; cii!=casadi_s2+4; ++cii, ++cs) rr[*cii] = *cs;
  /* #45: @16 = project(@0) */
  casadi_sparsify(w00, (&w16), casadi_s3, 0);
  /* #46: @21 = ones(17x1,3nz) */
  casadi_fill(w21, 3, 1.);
  /* #47: {@14, NULL, NULL, NULL, @17, @10} = vertsplit(@21) */
  w14 = w21[0];
  w17 = w21[1];
  w10 = w21[2];
  /* #48: @8 = dot(@16, @17) */
  w08 = casadi_dot(1, (&w16), (&w17));
  /* #49: @8 = (@8/@1) */
  w08 /= w01;
  /* #50: @16 = project(@4) */
  casadi_sparsify(w04, (&w16), casadi_s4, 0);
  /* #51: @17 = dot(@16, @14) */
  w17 = casadi_dot(1, (&w16), (&w14));
  /* #52: @17 = (@17/@3) */
  w17 /= w03;
  /* #53: @16 = project(@5) */
  casadi_sparsify(w05, (&w16), casadi_s4, 0);
  /* #54: @15 = dot(@16, @14) */
  w15 = casadi_dot(1, (&w16), (&w14));
  /* #55: @15 = (@15/@3) */
  w15 /= w03;
  /* #56: @16 = (@6*@17) */
  w16  = (w06*w17);
  /* #57: @15 = (@15-@16) */
  w15 -= w16;
  /* #58: @16 = project(@11) */
  casadi_sparsify(w11, (&w16), casadi_s4, 0);
  /* #59: @14 = dot(@16, @10) */
  w14 = casadi_dot(1, (&w16), (&w10));
  /* #60: @14 = (@14/@2) */
  w14 /= w02;
  /* #61: @20 = vertcat(@8, @17, @15, @18, @14) */
  rr=w20;
  *rr++ = w08;
  *rr++ = w17;
  *rr++ = w15;
  *rr++ = w14;
  /* #62: @19 = @20[:4] */
  for (rr=w19, cs=w20+0; cs!=w20+4; cs+=1) *rr++ = *cs;
  /* #63: (@12[1, 5, 8, 13] = @19) */
  for (cii=casadi_s5, rr=w12, cs=w19; cii!=casadi_s5+4; ++cii, ++cs) rr[*cii] = *cs;
  /* #64: @8 = project(@0) */
  casadi_sparsify(w00, (&w08), casadi_s6, 0);
  /* #65: @21 = ones(17x1,3nz) */
  casadi_fill(w21, 3, 1.);
  /* #66: {@17, NULL, NULL, NULL, @15, @14} = vertsplit(@21) */
  w17 = w21[0];
  w15 = w21[1];
  w14 = w21[2];
  /* #67: @16 = dot(@8, @15) */
  w16 = casadi_dot(1, (&w08), (&w15));
  /* #68: @16 = (@16/@1) */
  w16 /= w01;
  /* #69: @8 = project(@4) */
  casadi_sparsify(w04, (&w08), casadi_s7, 0);
  /* #70: @10 = dot(@8, @17) */
  w10 = casadi_dot(1, (&w08), (&w17));
  /* #71: @10 = (@10/@3) */
  w10 /= w03;
  /* #72: @8 = project(@5) */
  casadi_sparsify(w05, (&w08), casadi_s7, 0);
  /* #73: @22 = dot(@8, @17) */
  w22 = casadi_dot(1, (&w08), (&w17));
  /* #74: @22 = (@22/@3) */
  w22 /= w03;
  /* #75: @6 = (@6*@10) */
  w06 *= w10;
  /* #76: @22 = (@22-@6) */
  w22 -= w06;
  /* #77: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #78: @6 = @15[0] */
  for (rr=(&w06), cs=(&w15)+0; cs!=(&w15)+1; cs+=1) *rr++ = *cs;
  /* #79: @7 = (@7*@6) */
  w07 *= w06;
  /* #80: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #81: @7 = (-@7) */
  w07 = (- w07 );
  /* #82: @6 = project(@11) */
  casadi_sparsify(w11, (&w06), casadi_s7, 0);
  /* #83: @15 = dot(@6, @14) */
  w15 = casadi_dot(1, (&w06), (&w14));
  /* #84: @15 = (@15/@2) */
  w15 /= w02;
  /* #85: @23 = vertcat(@16, @10, @22, @7, @15) */
  rr=w23;
  *rr++ = w16;
  *rr++ = w10;
  *rr++ = w22;
  *rr++ = w07;
  *rr++ = w15;
  /* #86: (@12[2, 6, 9, 10, 14] = @23) */
  for (cii=casadi_s8, rr=w12, cs=w23; cii!=casadi_s8+5; ++cii, ++cs) rr[*cii] = *cs;
  /* #87: @16 = project(@0) */
  casadi_sparsify(w00, (&w16), casadi_s9, 0);
  /* #88: @10 = ones(17x1,1nz) */
  w10 = 1.;
  /* #89: {NULL, NULL, NULL, NULL, @22, NULL} = vertsplit(@10) */
  w22 = w10;
  /* #90: @10 = dot(@16, @22) */
  w10 = casadi_dot(1, (&w16), (&w22));
  /* #91: @10 = (@10/@1) */
  w10 /= w01;
  /* #92: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #93: @1 = @22[0] */
  for (rr=(&w01), cs=(&w22)+0; cs!=(&w22)+1; cs+=1) *rr++ = *cs;
  /* #94: @9 = (@9*@1) */
  w09 *= w01;
  /* #95: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #96: @9 = (-@9) */
  w09 = (- w09 );
  /* #97: @24 = vertcat(@10, @18, @18, @9, @18) */
  rr=w24;
  *rr++ = w10;
  *rr++ = w09;
  /* #98: @25 = @24[:2] */
  for (rr=w25, cs=w24+0; cs!=w24+2; cs+=1) *rr++ = *cs;
  /* #99: (@12[3:19:8] = @25) */
  for (rr=w12+3, cs=w25; rr!=w12+19; rr+=8) *rr = *cs++;
  /* #100: output[1][0] = @12 */
  casadi_copy(w12, 15, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int rocket_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rocket_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rocket_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rocket_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rocket_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rocket_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rocket_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void rocket_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rocket_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int rocket_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real rocket_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rocket_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rocket_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rocket_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    case 1: return casadi_s11;
    case 2: return casadi_s12;
    case 3: return casadi_s12;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rocket_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s13;
    case 1: return casadi_s14;
    case 2: return casadi_s15;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rocket_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 71;
  return 0;
}

CASADI_SYMBOL_EXPORT int rocket_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 9*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 71*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
