/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) rocket_constr_h_fun_jac_uxt_zt_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s1[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s2[4] = {0, 4, 7, 12};
static const casadi_int casadi_s3[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s4[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s5[4] = {1, 5, 8, 13};
static const casadi_int casadi_s6[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s7[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s8[5] = {2, 6, 9, 10, 14};
static const casadi_int casadi_s9[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s10[10] = 
  {0, 3, 6, 9, 13, 17, 21, 25,
  28, 31};
static const casadi_int casadi_s11[10] = 
  {1, 4, 7, 10, 14, 18, 22, 26,
  29, 32};
static const casadi_int casadi_s12[10] = 
  {2, 5, 8, 11, 15, 19, 23, 27,
  30, 33};
static const casadi_int casadi_s13[54] = 
  {17, 17, 0, 3, 6, 9, 9, 9,
  9, 9, 9, 9, 9, 13, 17, 21,
  25, 28, 31, 34, 0, 1, 2, 0,
  1, 2, 0, 1, 2, 10, 11, 12,
  13, 10, 11, 12, 13, 10, 11, 12,
  13, 10, 11, 12, 13, 14, 15, 16,
  14, 15, 16, 14, 15, 16};
static const casadi_int casadi_s14[3] = {14, 1, 1};
static const casadi_int casadi_s15[3] = {3, 1, 1};
static const casadi_int casadi_s16[3] = {5, 1, 1};
static const casadi_int casadi_s17[3] = {0, 1, 1};
static const casadi_int casadi_s18[23] = 
  {17, 5, 0, 4, 7, 10, 12, 15,
  10, 11, 12, 13, 0, 1, 2, 0,
  1, 2, 12, 13, 14, 15, 16};
static const casadi_int casadi_s19[3] = {5, 0, 1};
static const casadi_int casadi_s20[3] = {0, 0, 1};

static const casadi_real casadi_c0[3] = {0., 0., 1.};

/* rocket_constr_h_fun_jac_uxt_zt_hess:(i0[14],i1[3],i2[5],i3[0],i4[0])->(o0[5],o1[17x5,15nz],o2[17x17,34nz],o3[5x0],o4[]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w00=w+0, w01, w02, w03, *w04=w+7, *w05=w+10, w06, w07, w08, w09, w10;
  casadi_real *w11=w+18, *w12=w+21, *w13=w+36, w14, w15, w16, w17, w18, w20, *w21=w+52, *w22=w+56, *w23=w+60;
  casadi_real w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35;
  casadi_real w36, w37, w38, *w39=w+78, w40, *w41=w+84, *w42=w+86, *w43=w+88, w44, w45, w46, w47;
  casadi_real w48, w49, w50, *w51=w+129, *w52=w+132, *w54=w+135, *w55=w+145, *w56=w+149, *w57=w+153;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  /* #0: @0 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 4, w00);
  /* #1: @1 = ||@0||_F */
  w01 = casadi_norm_2(4, w00);
  /* #2: @2 = 1 */
  w02 = 1.;
  /* #3: @3 = (@1-@2) */
  w03  = (w01-w02);
  /* #4: output[0][0] = @3 */
  if (res[0]) res[0][0] = w03;
  /* #5: @4 = input[1][0] */
  casadi_copy(arg[1], 3, w04);
  /* #6: @3 = ||@4||_F */
  w03 = casadi_norm_2(3, w04);
  /* #7: output[0][1] = @3 */
  if (res[0]) res[0][1] = w03;
  /* #8: @5 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w05);
  /* #9: @6 = dot(@5, @4) */
  w06 = casadi_dot(3, w05, w04);
  /* #10: @6 = (@6/@3) */
  w06 /= w03;
  /* #11: output[0][2] = @6 */
  if (res[0]) res[0][2] = w06;
  /* #12: @7 = @0[2] */
  for (rr=(&w07), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #13: @8 = sq(@7) */
  w08 = casadi_sq( w07 );
  /* #14: @9 = @0[3] */
  for (rr=(&w09), cs=w00+3; cs!=w00+4; cs+=1) *rr++ = *cs;
  /* #15: @10 = sq(@9) */
  w10 = casadi_sq( w09 );
  /* #16: @8 = (@8+@10) */
  w08 += w10;
  /* #17: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #18: @2 = (@2-@8) */
  w02 -= w08;
  /* #19: output[0][3] = @2 */
  if (res[0]) res[0][3] = w02;
  /* #20: @11 = input[0][4] */
  casadi_copy(arg[0] ? arg[0]+11 : 0, 3, w11);
  /* #21: @2 = ||@11||_F */
  w02 = casadi_norm_2(3, w11);
  /* #22: output[0][4] = @2 */
  if (res[0]) res[0][4] = w02;
  /* #23: @12 = zeros(17x5,15nz) */
  casadi_clear(w12, 15);
  /* #24: @8 = project(@0) */
  casadi_sparsify(w00, (&w08), casadi_s0, 0);
  /* #25: @13 = ones(17x1,10nz) */
  casadi_fill(w13, 10, 1.);
  /* #26: {@10, NULL, NULL, NULL, @14, @15} = vertsplit(@13) */
  w10 = w13[0];
  w14 = w13[8];
  w15 = w13[9];
  /* #27: @16 = dot(@8, @14) */
  w16 = casadi_dot(1, (&w08), (&w14));
  /* #28: @16 = (@16/@1) */
  w16 /= w01;
  /* #29: @8 = project(@4) */
  casadi_sparsify(w04, (&w08), casadi_s1, 0);
  /* #30: @17 = dot(@8, @10) */
  w17 = casadi_dot(1, (&w08), (&w10));
  /* #31: @17 = (@17/@3) */
  w17 /= w03;
  /* #32: @8 = project(@5) */
  casadi_sparsify(w05, (&w08), casadi_s1, 0);
  /* #33: @18 = dot(@8, @10) */
  w18 = casadi_dot(1, (&w08), (&w10));
  /* #34: @18 = (@18/@3) */
  w18 /= w03;
  /* #35: @6 = (@6/@3) */
  w06 /= w03;
  /* #36: @8 = (@6*@17) */
  w08  = (w06*w17);
  /* #37: @18 = (@18-@8) */
  w18 -= w08;
  /* #38: @19 = 00 */
  /* #39: @8 = project(@11) */
  casadi_sparsify(w11, (&w08), casadi_s1, 0);
  /* #40: @20 = dot(@8, @15) */
  w20 = casadi_dot(1, (&w08), (&w15));
  /* #41: @20 = (@20/@2) */
  w20 /= w02;
  /* #42: @21 = vertcat(@16, @17, @18, @19, @20) */
  rr=w21;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w20;
  /* #43: @22 = @21[:4] */
  for (rr=w22, cs=w21+0; cs!=w21+4; cs+=1) *rr++ = *cs;
  /* #44: (@12[0, 4, 7, 12] = @22) */
  for (cii=casadi_s2, rr=w12, cs=w22; cii!=casadi_s2+4; ++cii, ++cs) rr[*cii] = *cs;
  /* #45: @8 = project(@0) */
  casadi_sparsify(w00, (&w08), casadi_s3, 0);
  /* #46: @23 = ones(17x1,3nz) */
  casadi_fill(w23, 3, 1.);
  /* #47: {@24, NULL, NULL, NULL, @25, @26} = vertsplit(@23) */
  w24 = w23[0];
  w25 = w23[1];
  w26 = w23[2];
  /* #48: @27 = dot(@8, @25) */
  w27 = casadi_dot(1, (&w08), (&w25));
  /* #49: @27 = (@27/@1) */
  w27 /= w01;
  /* #50: @8 = project(@4) */
  casadi_sparsify(w04, (&w08), casadi_s4, 0);
  /* #51: @28 = dot(@8, @24) */
  w28 = casadi_dot(1, (&w08), (&w24));
  /* #52: @28 = (@28/@3) */
  w28 /= w03;
  /* #53: @8 = project(@5) */
  casadi_sparsify(w05, (&w08), casadi_s4, 0);
  /* #54: @29 = dot(@8, @24) */
  w29 = casadi_dot(1, (&w08), (&w24));
  /* #55: @29 = (@29/@3) */
  w29 /= w03;
  /* #56: @8 = (@6*@28) */
  w08  = (w06*w28);
  /* #57: @29 = (@29-@8) */
  w29 -= w08;
  /* #58: @8 = project(@11) */
  casadi_sparsify(w11, (&w08), casadi_s4, 0);
  /* #59: @30 = dot(@8, @26) */
  w30 = casadi_dot(1, (&w08), (&w26));
  /* #60: @30 = (@30/@2) */
  w30 /= w02;
  /* #61: @22 = vertcat(@27, @28, @29, @19, @30) */
  rr=w22;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  /* #62: @21 = @22[:4] */
  for (rr=w21, cs=w22+0; cs!=w22+4; cs+=1) *rr++ = *cs;
  /* #63: (@12[1, 5, 8, 13] = @21) */
  for (cii=casadi_s5, rr=w12, cs=w21; cii!=casadi_s5+4; ++cii, ++cs) rr[*cii] = *cs;
  /* #64: @8 = project(@0) */
  casadi_sparsify(w00, (&w08), casadi_s6, 0);
  /* #65: @23 = ones(17x1,3nz) */
  casadi_fill(w23, 3, 1.);
  /* #66: {@31, NULL, NULL, NULL, @32, @33} = vertsplit(@23) */
  w31 = w23[0];
  w32 = w23[1];
  w33 = w23[2];
  /* #67: @34 = dot(@8, @32) */
  w34 = casadi_dot(1, (&w08), (&w32));
  /* #68: @34 = (@34/@1) */
  w34 /= w01;
  /* #69: @8 = project(@4) */
  casadi_sparsify(w04, (&w08), casadi_s7, 0);
  /* #70: @35 = dot(@8, @31) */
  w35 = casadi_dot(1, (&w08), (&w31));
  /* #71: @35 = (@35/@3) */
  w35 /= w03;
  /* #72: @8 = project(@5) */
  casadi_sparsify(w05, (&w08), casadi_s7, 0);
  /* #73: @36 = dot(@8, @31) */
  w36 = casadi_dot(1, (&w08), (&w31));
  /* #74: @36 = (@36/@3) */
  w36 /= w03;
  /* #75: @8 = (@6*@35) */
  w08  = (w06*w35);
  /* #76: @36 = (@36-@8) */
  w36 -= w08;
  /* #77: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #78: @8 = @32[0] */
  for (rr=(&w08), cs=(&w32)+0; cs!=(&w32)+1; cs+=1) *rr++ = *cs;
  /* #79: @7 = (@7*@8) */
  w07 *= w08;
  /* #80: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #81: @7 = (-@7) */
  w07 = (- w07 );
  /* #82: @37 = project(@11) */
  casadi_sparsify(w11, (&w37), casadi_s7, 0);
  /* #83: @38 = dot(@37, @33) */
  w38 = casadi_dot(1, (&w37), (&w33));
  /* #84: @38 = (@38/@2) */
  w38 /= w02;
  /* #85: @39 = vertcat(@34, @35, @36, @7, @38) */
  rr=w39;
  *rr++ = w34;
  *rr++ = w35;
  *rr++ = w36;
  *rr++ = w07;
  *rr++ = w38;
  /* #86: (@12[2, 6, 9, 10, 14] = @39) */
  for (cii=casadi_s8, rr=w12, cs=w39; cii!=casadi_s8+5; ++cii, ++cs) rr[*cii] = *cs;
  /* #87: @7 = project(@0) */
  casadi_sparsify(w00, (&w07), casadi_s9, 0);
  /* #88: @37 = ones(17x1,1nz) */
  w37 = 1.;
  /* #89: {NULL, NULL, NULL, NULL, @40, NULL} = vertsplit(@37) */
  w40 = w37;
  /* #90: @37 = dot(@7, @40) */
  w37 = casadi_dot(1, (&w07), (&w40));
  /* #91: @37 = (@37/@1) */
  w37 /= w01;
  /* #92: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #93: @7 = @40[0] */
  for (rr=(&w07), cs=(&w40)+0; cs!=(&w40)+1; cs+=1) *rr++ = *cs;
  /* #94: @9 = (@9*@7) */
  w09 *= w07;
  /* #95: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #96: @9 = (-@9) */
  w09 = (- w09 );
  /* #97: @41 = vertcat(@37, @19, @19, @9, @19) */
  rr=w41;
  *rr++ = w37;
  *rr++ = w09;
  /* #98: @42 = @41[:2] */
  for (rr=w42, cs=w41+0; cs!=w41+2; cs+=1) *rr++ = *cs;
  /* #99: (@12[3:19:8] = @42) */
  for (rr=w12+3, cs=w42; rr!=w12+19; rr+=8) *rr = *cs++;
  /* #100: output[1][0] = @12 */
  casadi_copy(w12, 15, res[1]);
  /* #101: @43 = zeros(17x17,34nz) */
  casadi_clear(w43, 34);
  /* #102: @39 = input[2][0] */
  casadi_copy(arg[2], 5, w39);
  /* #103: {@9, @44, @45, @46, @47} = vertsplit(@39) */
  w09 = w39[0];
  w44 = w39[1];
  w45 = w39[2];
  w46 = w39[3];
  w47 = w39[4];
  /* #104: @18 = (@18/@3) */
  w18 /= w03;
  /* #105: @48 = (@6/@3) */
  w48  = (w06/w03);
  /* #106: @49 = (@48*@17) */
  w49  = (w48*w17);
  /* #107: @18 = (@18-@49) */
  w18 -= w49;
  /* #108: @18 = (@45*@18) */
  w18  = (w45*w18);
  /* #109: @18 = (@18/@3) */
  w18 /= w03;
  /* #110: @6 = (@6*@45) */
  w06 *= w45;
  /* #111: @6 = (@6/@3) */
  w06 /= w03;
  /* #112: @49 = (@6/@3) */
  w49  = (w06/w03);
  /* #113: @50 = (@49*@17) */
  w50  = (w49*w17);
  /* #114: @18 = (@18-@50) */
  w18 -= w50;
  /* #115: @23 = (@4*@18) */
  for (i=0, rr=w23, cr=w04; i<3; ++i) (*rr++)  = ((*cr++)*w18);
  /* #116: @18 = (@6*@10) */
  w18  = (w06*w10);
  /* #117: @51 = dense(@18) */
  casadi_densify((&w18), casadi_s1, w51, 0);
  /* #118: @23 = (@23+@51) */
  for (i=0, rr=w23, cs=w51; i<3; ++i) (*rr++) += (*cs++);
  /* #119: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) *rr++ = (- *cs++ );
  /* #120: @18 = (@45/@3) */
  w18  = (w45/w03);
  /* #121: @18 = (@18/@3) */
  w18 /= w03;
  /* #122: @50 = (@18*@17) */
  w50  = (w18*w17);
  /* #123: @51 = (@5*@50) */
  for (i=0, rr=w51, cr=w05; i<3; ++i) (*rr++)  = ((*cr++)*w50);
  /* #124: @23 = (@23-@51) */
  for (i=0, rr=w23, cs=w51; i<3; ++i) (*rr++) -= (*cs++);
  /* #125: @44 = (@44/@3) */
  w44 /= w03;
  /* #126: @10 = (@44*@10) */
  w10  = (w44*w10);
  /* #127: @51 = dense(@10) */
  casadi_densify((&w10), casadi_s1, w51, 0);
  /* #128: @10 = (@44/@3) */
  w10  = (w44/w03);
  /* #129: @17 = (@10*@17) */
  w17  = (w10*w17);
  /* #130: @52 = (@4*@17) */
  for (i=0, rr=w52, cr=w04; i<3; ++i) (*rr++)  = ((*cr++)*w17);
  /* #131: @51 = (@51-@52) */
  for (i=0, rr=w51, cs=w52; i<3; ++i) (*rr++) -= (*cs++);
  /* #132: @23 = (@23+@51) */
  for (i=0, rr=w23, cs=w51; i<3; ++i) (*rr++) += (*cs++);
  /* #133: @53 = zeros(3x1,0nz) */
  /* #134: @9 = (@9/@1) */
  w09 /= w01;
  /* #135: @14 = (@9*@14) */
  w14  = (w09*w14);
  /* #136: @21 = dense(@14) */
  casadi_densify((&w14), casadi_s0, w21, 0);
  /* #137: @1 = (@9/@1) */
  w01  = (w09/w01);
  /* #138: @16 = (@1*@16) */
  w16  = (w01*w16);
  /* #139: @22 = (@0*@16) */
  for (i=0, rr=w22, cr=w00; i<4; ++i) (*rr++)  = ((*cr++)*w16);
  /* #140: @21 = (@21-@22) */
  for (i=0, rr=w21, cs=w22; i<4; ++i) (*rr++) -= (*cs++);
  /* #141: @47 = (@47/@2) */
  w47 /= w02;
  /* #142: @15 = (@47*@15) */
  w15  = (w47*w15);
  /* #143: @51 = dense(@15) */
  casadi_densify((&w15), casadi_s1, w51, 0);
  /* #144: @2 = (@47/@2) */
  w02  = (w47/w02);
  /* #145: @20 = (@2*@20) */
  w20  = (w02*w20);
  /* #146: @52 = (@11*@20) */
  for (i=0, rr=w52, cr=w11; i<3; ++i) (*rr++)  = ((*cr++)*w20);
  /* #147: @51 = (@51-@52) */
  for (i=0, rr=w51, cs=w52; i<3; ++i) (*rr++) -= (*cs++);
  /* #148: @13 = vertcat(@23, @19, @53, @53, @21, @51) */
  rr=w13;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w51; i<3; ++i) *rr++ = *cs++;
  /* #149: @54 = @13[:10] */
  for (rr=w54, cs=w13+0; cs!=w13+10; cs+=1) *rr++ = *cs;
  /* #150: (@43[0, 3, 6, 9, 13, 17, 21, 25, 28, 31] = @54) */
  for (cii=casadi_s10, rr=w43, cs=w54; cii!=casadi_s10+10; ++cii, ++cs) rr[*cii] = *cs;
  /* #151: @29 = (@29/@3) */
  w29 /= w03;
  /* #152: @20 = (@48*@28) */
  w20  = (w48*w28);
  /* #153: @29 = (@29-@20) */
  w29 -= w20;
  /* #154: @29 = (@45*@29) */
  w29  = (w45*w29);
  /* #155: @29 = (@29/@3) */
  w29 /= w03;
  /* #156: @20 = (@49*@28) */
  w20  = (w49*w28);
  /* #157: @29 = (@29-@20) */
  w29 -= w20;
  /* #158: @23 = (@4*@29) */
  for (i=0, rr=w23, cr=w04; i<3; ++i) (*rr++)  = ((*cr++)*w29);
  /* #159: @29 = (@6*@24) */
  w29  = (w06*w24);
  /* #160: @51 = dense(@29) */
  casadi_densify((&w29), casadi_s4, w51, 0);
  /* #161: @23 = (@23+@51) */
  for (i=0, rr=w23, cs=w51; i<3; ++i) (*rr++) += (*cs++);
  /* #162: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) *rr++ = (- *cs++ );
  /* #163: @29 = (@18*@28) */
  w29  = (w18*w28);
  /* #164: @51 = (@5*@29) */
  for (i=0, rr=w51, cr=w05; i<3; ++i) (*rr++)  = ((*cr++)*w29);
  /* #165: @23 = (@23-@51) */
  for (i=0, rr=w23, cs=w51; i<3; ++i) (*rr++) -= (*cs++);
  /* #166: @24 = (@44*@24) */
  w24  = (w44*w24);
  /* #167: @51 = dense(@24) */
  casadi_densify((&w24), casadi_s4, w51, 0);
  /* #168: @28 = (@10*@28) */
  w28  = (w10*w28);
  /* #169: @52 = (@4*@28) */
  for (i=0, rr=w52, cr=w04; i<3; ++i) (*rr++)  = ((*cr++)*w28);
  /* #170: @51 = (@51-@52) */
  for (i=0, rr=w51, cs=w52; i<3; ++i) (*rr++) -= (*cs++);
  /* #171: @23 = (@23+@51) */
  for (i=0, rr=w23, cs=w51; i<3; ++i) (*rr++) += (*cs++);
  /* #172: @25 = (@9*@25) */
  w25  = (w09*w25);
  /* #173: @21 = dense(@25) */
  casadi_densify((&w25), casadi_s3, w21, 0);
  /* #174: @27 = (@1*@27) */
  w27  = (w01*w27);
  /* #175: @22 = (@0*@27) */
  for (i=0, rr=w22, cr=w00; i<4; ++i) (*rr++)  = ((*cr++)*w27);
  /* #176: @21 = (@21-@22) */
  for (i=0, rr=w21, cs=w22; i<4; ++i) (*rr++) -= (*cs++);
  /* #177: @26 = (@47*@26) */
  w26  = (w47*w26);
  /* #178: @51 = dense(@26) */
  casadi_densify((&w26), casadi_s4, w51, 0);
  /* #179: @30 = (@2*@30) */
  w30  = (w02*w30);
  /* #180: @52 = (@11*@30) */
  for (i=0, rr=w52, cr=w11; i<3; ++i) (*rr++)  = ((*cr++)*w30);
  /* #181: @51 = (@51-@52) */
  for (i=0, rr=w51, cs=w52; i<3; ++i) (*rr++) -= (*cs++);
  /* #182: @54 = vertcat(@23, @19, @53, @53, @21, @51) */
  rr=w54;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w51; i<3; ++i) *rr++ = *cs++;
  /* #183: @13 = @54[:10] */
  for (rr=w13, cs=w54+0; cs!=w54+10; cs+=1) *rr++ = *cs;
  /* #184: (@43[1, 4, 7, 10, 14, 18, 22, 26, 29, 32] = @13) */
  for (cii=casadi_s11, rr=w43, cs=w13; cii!=casadi_s11+10; ++cii, ++cs) rr[*cii] = *cs;
  /* #185: @36 = (@36/@3) */
  w36 /= w03;
  /* #186: @48 = (@48*@35) */
  w48 *= w35;
  /* #187: @36 = (@36-@48) */
  w36 -= w48;
  /* #188: @45 = (@45*@36) */
  w45 *= w36;
  /* #189: @45 = (@45/@3) */
  w45 /= w03;
  /* #190: @49 = (@49*@35) */
  w49 *= w35;
  /* #191: @45 = (@45-@49) */
  w45 -= w49;
  /* #192: @23 = (@4*@45) */
  for (i=0, rr=w23, cr=w04; i<3; ++i) (*rr++)  = ((*cr++)*w45);
  /* #193: @6 = (@6*@31) */
  w06 *= w31;
  /* #194: @51 = dense(@6) */
  casadi_densify((&w06), casadi_s7, w51, 0);
  /* #195: @23 = (@23+@51) */
  for (i=0, rr=w23, cs=w51; i<3; ++i) (*rr++) += (*cs++);
  /* #196: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) *rr++ = (- *cs++ );
  /* #197: @18 = (@18*@35) */
  w18 *= w35;
  /* #198: @5 = (@5*@18) */
  for (i=0, rr=w05; i<3; ++i) (*rr++) *= w18;
  /* #199: @23 = (@23-@5) */
  for (i=0, rr=w23, cs=w05; i<3; ++i) (*rr++) -= (*cs++);
  /* #200: @44 = (@44*@31) */
  w44 *= w31;
  /* #201: @5 = dense(@44) */
  casadi_densify((&w44), casadi_s7, w05, 0);
  /* #202: @10 = (@10*@35) */
  w10 *= w35;
  /* #203: @4 = (@4*@10) */
  for (i=0, rr=w04; i<3; ++i) (*rr++) *= w10;
  /* #204: @5 = (@5-@4) */
  for (i=0, rr=w05, cs=w04; i<3; ++i) (*rr++) -= (*cs++);
  /* #205: @23 = (@23+@5) */
  for (i=0, rr=w23, cs=w05; i<3; ++i) (*rr++) += (*cs++);
  /* #206: @21 = zeros(4x1) */
  casadi_clear(w21, 4);
  /* #207: @46 = (-@46) */
  w46 = (- w46 );
  /* #208: @46 = (2.*@46) */
  w46 = (2.* w46 );
  /* #209: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #210: @8 = (@46*@8) */
  w08  = (w46*w08);
  /* #211: @22 = @21; (@22[2] += @8) */
  casadi_copy(w21, 4, w22);
  for (rr=w22+2, cs=(&w08); rr!=w22+3; rr+=1) *rr += *cs++;
  /* #212: @32 = (@9*@32) */
  w32  = (w09*w32);
  /* #213: @55 = dense(@32) */
  casadi_densify((&w32), casadi_s6, w55, 0);
  /* #214: @34 = (@1*@34) */
  w34  = (w01*w34);
  /* #215: @56 = (@0*@34) */
  for (i=0, rr=w56, cr=w00; i<4; ++i) (*rr++)  = ((*cr++)*w34);
  /* #216: @55 = (@55-@56) */
  for (i=0, rr=w55, cs=w56; i<4; ++i) (*rr++) -= (*cs++);
  /* #217: @22 = (@22+@55) */
  for (i=0, rr=w22, cs=w55; i<4; ++i) (*rr++) += (*cs++);
  /* #218: @47 = (@47*@33) */
  w47 *= w33;
  /* #219: @5 = dense(@47) */
  casadi_densify((&w47), casadi_s7, w05, 0);
  /* #220: @2 = (@2*@38) */
  w02 *= w38;
  /* #221: @11 = (@11*@2) */
  for (i=0, rr=w11; i<3; ++i) (*rr++) *= w02;
  /* #222: @5 = (@5-@11) */
  for (i=0, rr=w05, cs=w11; i<3; ++i) (*rr++) -= (*cs++);
  /* #223: @13 = vertcat(@23, @19, @53, @53, @22, @5) */
  rr=w13;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w05; i<3; ++i) *rr++ = *cs++;
  /* #224: @54 = @13[:10] */
  for (rr=w54, cs=w13+0; cs!=w13+10; cs+=1) *rr++ = *cs;
  /* #225: (@43[2, 5, 8, 11, 15, 19, 23, 27, 30, 33] = @54) */
  for (cii=casadi_s12, rr=w43, cs=w54; cii!=casadi_s12+10; ++cii, ++cs) rr[*cii] = *cs;
  /* #226: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #227: @46 = (@46*@7) */
  w46 *= w07;
  /* #228: (@21[3] += @46) */
  for (rr=w21+3, cs=(&w46); rr!=w21+4; rr+=1) *rr += *cs++;
  /* #229: @9 = (@9*@40) */
  w09 *= w40;
  /* #230: @22 = dense(@9) */
  casadi_densify((&w09), casadi_s9, w22, 0);
  /* #231: @1 = (@1*@37) */
  w01 *= w37;
  /* #232: @0 = (@0*@1) */
  for (i=0, rr=w00; i<4; ++i) (*rr++) *= w01;
  /* #233: @22 = (@22-@0) */
  for (i=0, rr=w22, cs=w00; i<4; ++i) (*rr++) -= (*cs++);
  /* #234: @21 = (@21+@22) */
  for (i=0, rr=w21, cs=w22; i<4; ++i) (*rr++) += (*cs++);
  /* #235: (@43[12:28:4] = @21) */
  for (rr=w43+12, cs=w21; rr!=w43+28; rr+=4) *rr = *cs++;
  /* #236: @57 = @43' */
  casadi_trans(w43,casadi_s13, w57, casadi_s13, iw);
  /* #237: output[2][0] = @57 */
  casadi_copy(w57, 34, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int rocket_constr_h_fun_jac_uxt_zt_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rocket_constr_h_fun_jac_uxt_zt_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rocket_constr_h_fun_jac_uxt_zt_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rocket_constr_h_fun_jac_uxt_zt_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rocket_constr_h_fun_jac_uxt_zt_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rocket_constr_h_fun_jac_uxt_zt_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rocket_constr_h_fun_jac_uxt_zt_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void rocket_constr_h_fun_jac_uxt_zt_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rocket_constr_h_fun_jac_uxt_zt_hess_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int rocket_constr_h_fun_jac_uxt_zt_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real rocket_constr_h_fun_jac_uxt_zt_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rocket_constr_h_fun_jac_uxt_zt_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rocket_constr_h_fun_jac_uxt_zt_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rocket_constr_h_fun_jac_uxt_zt_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s14;
    case 1: return casadi_s15;
    case 2: return casadi_s16;
    case 3: return casadi_s17;
    case 4: return casadi_s17;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rocket_constr_h_fun_jac_uxt_zt_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s16;
    case 1: return casadi_s18;
    case 2: return casadi_s13;
    case 3: return casadi_s19;
    case 4: return casadi_s20;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rocket_constr_h_fun_jac_uxt_zt_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 11;
  if (sz_iw) *sz_iw = 18;
  if (sz_w) *sz_w = 187;
  return 0;
}

CASADI_SYMBOL_EXPORT int rocket_constr_h_fun_jac_uxt_zt_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 11*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 18*sizeof(casadi_int);
  if (sz_w) *sz_w = 187*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
