/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) rocket_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s1[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s2[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s3[12] = 
  {2, 3, 0, 2, 4, 6, 0, 1,
  0, 1, 0, 1};
static const casadi_int casadi_s4[5] = {0, 4, 7, 12, 15};
static const casadi_int casadi_s5[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s6[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s7[5] = {1, 5, 8, 13, 16};
static const casadi_int casadi_s8[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s9[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s10[6] = {2, 6, 9, 10, 14, 17};
static const casadi_int casadi_s11[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s12[3] = {15, 1, 1};
static const casadi_int casadi_s13[3] = {3, 1, 1};
static const casadi_int casadi_s14[3] = {0, 1, 1};
static const casadi_int casadi_s15[3] = {6, 1, 1};
static const casadi_int casadi_s16[27] = 
  {18, 6, 0, 4, 7, 10, 12, 15,
  18, 10, 11, 12, 13, 0, 1, 2,
  0, 1, 2, 12, 13, 14, 15, 16,
  4, 5, 6};
static const casadi_int casadi_s17[3] = {6, 0, 1};

static const casadi_real casadi_c0[3] = {0., 0., 1.};
static const casadi_real casadi_c1[3] = {1., 0., 0.};
static const casadi_real casadi_c2[3] = {0., 1., 0.};

/* rocket_constr_h_fun_jac_uxt_zt:(i0[15],i1[3],i2[0],i3[0])->(o0[6],o1[18x6,18nz],o2[6x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w00=w+2, w01, w02, w03, *w04=w+9, *w05=w+12, w06, w07, w08, w09, w10;
  casadi_real *w11=w+20, *w12=w+23, *w13=w+26, *w14=w+28, *w15=w+31, *w16=w+34, *w17=w+40, *w18=w+46, *w19=w+48, w20, *w21=w+67, w22;
  casadi_real w23, w24, w25, w26, w27, w29, w30, *w31=w+84, *w32=w+86, *w33=w+91, *w34=w+96;
  const casadi_int *cii;
  const casadi_real *cs, *ct;
  /* #0: @0 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 4, w00);
  /* #1: @1 = ||@0||_F */
  w01 = casadi_norm_2(4, w00);
  /* #2: @2 = 1 */
  w02 = 1.;
  /* #3: @3 = (@1-@2) */
  w03  = (w01-w02);
  /* #4: output[0][0] = @3 */
  if (res[0]) res[0][0] = w03;
  /* #5: @4 = input[1][0] */
  casadi_copy(arg[1], 3, w04);
  /* #6: @3 = ||@4||_F */
  w03 = casadi_norm_2(3, w04);
  /* #7: output[0][1] = @3 */
  if (res[0]) res[0][1] = w03;
  /* #8: @5 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w05);
  /* #9: @6 = dot(@5, @4) */
  w06 = casadi_dot(3, w05, w04);
  /* #10: @7 = 0.965926 */
  w07 = 9.6592582628906831e-01;
  /* #11: @8 = (@7*@3) */
  w08  = (w07*w03);
  /* #12: @6 = (@6-@8) */
  w06 -= w08;
  /* #13: output[0][2] = @6 */
  if (res[0]) res[0][2] = w06;
  /* #14: @6 = @0[2] */
  for (rr=(&w06), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #15: @8 = sq(@6) */
  w08 = casadi_sq( w06 );
  /* #16: @9 = @0[3] */
  for (rr=(&w09), cs=w00+3; cs!=w00+4; cs+=1) *rr++ = *cs;
  /* #17: @10 = sq(@9) */
  w10 = casadi_sq( w09 );
  /* #18: @8 = (@8+@10) */
  w08 += w10;
  /* #19: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #20: @2 = (@2-@8) */
  w02 -= w08;
  /* #21: output[0][3] = @2 */
  if (res[0]) res[0][3] = w02;
  /* #22: @11 = input[0][4] */
  casadi_copy(arg[0] ? arg[0]+11 : 0, 3, w11);
  /* #23: @2 = dot(@11, @11) */
  w02 = casadi_dot(3, w11, w11);
  /* #24: output[0][4] = @2 */
  if (res[0]) res[0][4] = w02;
  /* #25: @12 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+1 : 0, 3, w12);
  /* #26: @2 = dot(@5, @12) */
  w02 = casadi_dot(3, w05, w12);
  /* #27: @8 = 1e-05 */
  w08 = 1.0000000000000001e-05;
  /* #28: @13 = zeros(2x1) */
  casadi_clear(w13, 2);
  /* #29: @14 = [1, 0, 0] */
  casadi_copy(casadi_c1, 3, w14);
  /* #30: @15 = [0, 1, 0] */
  casadi_copy(casadi_c2, 3, w15);
  /* #31: @16 = horzcat(@14, @15) */
  rr=w16;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  /* #32: @17 = @16' */
  for (i=0, rr=w17, cs=w16; i<2; ++i) for (j=0; j<3; ++j) rr[i+j*2] = *cs++;
  /* #33: @18 = mac(@17,@12,@13) */
  casadi_copy(w13, 2, w18);
  for (i=0, rr=w18; i<1; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, cs=w17+j, ct=w12+i*3; k<3; ++k) *rr += cs[k*2]**ct++;
  /* #34: @10 = ||@18||_F */
  w10 = casadi_norm_2(2, w18);
  /* #35: @8 = (@8+@10) */
  w08 += w10;
  /* #36: @2 = (@2/@8) */
  w02 /= w08;
  /* #37: output[0][5] = @2 */
  if (res[0]) res[0][5] = w02;
  /* #38: @19 = zeros(18x6,18nz) */
  casadi_clear(w19, 18);
  /* #39: @20 = project(@0) */
  casadi_sparsify(w00, (&w20), casadi_s0, 0);
  /* #40: @21 = ones(18x1,9nz) */
  casadi_fill(w21, 9, 1.);
  /* #41: {@22, NULL, @23, NULL, @24, @25, NULL} = vertsplit(@21) */
  w22 = w21[0];
  w23 = w21[2];
  w24 = w21[6];
  w25 = w21[7];
  /* #42: @26 = dot(@20, @24) */
  w26 = casadi_dot(1, (&w20), (&w24));
  /* #43: @26 = (@26/@1) */
  w26 /= w01;
  /* #44: @20 = project(@4) */
  casadi_sparsify(w04, (&w20), casadi_s1, 0);
  /* #45: @24 = dot(@20, @22) */
  w24 = casadi_dot(1, (&w20), (&w22));
  /* #46: @24 = (@24/@3) */
  w24 /= w03;
  /* #47: @20 = project(@5) */
  casadi_sparsify(w05, (&w20), casadi_s1, 0);
  /* #48: @27 = dot(@20, @22) */
  w27 = casadi_dot(1, (&w20), (&w22));
  /* #49: @22 = (@7*@24) */
  w22  = (w07*w24);
  /* #50: @27 = (@27-@22) */
  w27 -= w22;
  /* #51: @28 = 00 */
  /* #52: @22 = project(@11) */
  casadi_sparsify(w11, (&w22), casadi_s1, 0);
  /* #53: @29 = dot(@22, @25) */
  w29 = casadi_dot(1, (&w22), (&w25));
  /* #54: @30 = dot(@25, @22) */
  w30 = casadi_dot(1, (&w25), (&w22));
  /* #55: @29 = (@29+@30) */
  w29 += w30;
  /* #56: @30 = dot(@20, @23) */
  w30 = casadi_dot(1, (&w20), (&w23));
  /* #57: @30 = (@30/@8) */
  w30 /= w08;
  /* #58: @2 = (@2/@8) */
  w02 /= w08;
  /* #59: @31 = mac(@17,@23,@13) */
  casadi_copy(w13, 2, w31);
  casadi_mtimes(w17, casadi_s3, (&w23), casadi_s1, w31, casadi_s2, w, 0);
  /* #60: @23 = dot(@18, @31) */
  w23 = casadi_dot(2, w18, w31);
  /* #61: @23 = (@23/@10) */
  w23 /= w10;
  /* #62: @23 = (@2*@23) */
  w23  = (w02*w23);
  /* #63: @30 = (@30-@23) */
  w30 -= w23;
  /* #64: @32 = vertcat(@26, @24, @27, @28, @29, @30) */
  rr=w32;
  *rr++ = w26;
  *rr++ = w24;
  *rr++ = w27;
  *rr++ = w29;
  *rr++ = w30;
  /* #65: @33 = @32[:5] */
  for (rr=w33, cs=w32+0; cs!=w32+5; cs+=1) *rr++ = *cs;
  /* #66: (@19[0, 4, 7, 12, 15] = @33) */
  for (cii=casadi_s4, rr=w19, cs=w33; cii!=casadi_s4+5; ++cii, ++cs) rr[*cii] = *cs;
  /* #67: @26 = project(@0) */
  casadi_sparsify(w00, (&w26), casadi_s5, 0);
  /* #68: @34 = ones(18x1,4nz) */
  casadi_fill(w34, 4, 1.);
  /* #69: {@24, NULL, @27, NULL, @29, @30, NULL} = vertsplit(@34) */
  w24 = w34[0];
  w27 = w34[1];
  w29 = w34[2];
  w30 = w34[3];
  /* #70: @23 = dot(@26, @29) */
  w23 = casadi_dot(1, (&w26), (&w29));
  /* #71: @23 = (@23/@1) */
  w23 /= w01;
  /* #72: @26 = project(@4) */
  casadi_sparsify(w04, (&w26), casadi_s6, 0);
  /* #73: @29 = dot(@26, @24) */
  w29 = casadi_dot(1, (&w26), (&w24));
  /* #74: @29 = (@29/@3) */
  w29 /= w03;
  /* #75: @26 = project(@5) */
  casadi_sparsify(w05, (&w26), casadi_s6, 0);
  /* #76: @20 = dot(@26, @24) */
  w20 = casadi_dot(1, (&w26), (&w24));
  /* #77: @24 = (@7*@29) */
  w24  = (w07*w29);
  /* #78: @20 = (@20-@24) */
  w20 -= w24;
  /* #79: @24 = project(@11) */
  casadi_sparsify(w11, (&w24), casadi_s6, 0);
  /* #80: @25 = dot(@24, @30) */
  w25 = casadi_dot(1, (&w24), (&w30));
  /* #81: @22 = dot(@30, @24) */
  w22 = casadi_dot(1, (&w30), (&w24));
  /* #82: @25 = (@25+@22) */
  w25 += w22;
  /* #83: @22 = dot(@26, @27) */
  w22 = casadi_dot(1, (&w26), (&w27));
  /* #84: @22 = (@22/@8) */
  w22 /= w08;
  /* #85: @31 = mac(@17,@27,@13) */
  casadi_copy(w13, 2, w31);
  casadi_mtimes(w17, casadi_s3, (&w27), casadi_s6, w31, casadi_s2, w, 0);
  /* #86: @27 = dot(@18, @31) */
  w27 = casadi_dot(2, w18, w31);
  /* #87: @27 = (@27/@10) */
  w27 /= w10;
  /* #88: @27 = (@2*@27) */
  w27  = (w02*w27);
  /* #89: @22 = (@22-@27) */
  w22 -= w27;
  /* #90: @33 = vertcat(@23, @29, @20, @28, @25, @22) */
  rr=w33;
  *rr++ = w23;
  *rr++ = w29;
  *rr++ = w20;
  *rr++ = w25;
  *rr++ = w22;
  /* #91: @32 = @33[:5] */
  for (rr=w32, cs=w33+0; cs!=w33+5; cs+=1) *rr++ = *cs;
  /* #92: (@19[1, 5, 8, 13, 16] = @32) */
  for (cii=casadi_s7, rr=w19, cs=w32; cii!=casadi_s7+5; ++cii, ++cs) rr[*cii] = *cs;
  /* #93: @23 = project(@0) */
  casadi_sparsify(w00, (&w23), casadi_s8, 0);
  /* #94: @34 = ones(18x1,4nz) */
  casadi_fill(w34, 4, 1.);
  /* #95: {@29, NULL, @20, NULL, @25, @22, NULL} = vertsplit(@34) */
  w29 = w34[0];
  w20 = w34[1];
  w25 = w34[2];
  w22 = w34[3];
  /* #96: @27 = dot(@23, @25) */
  w27 = casadi_dot(1, (&w23), (&w25));
  /* #97: @27 = (@27/@1) */
  w27 /= w01;
  /* #98: @23 = project(@4) */
  casadi_sparsify(w04, (&w23), casadi_s9, 0);
  /* #99: @26 = dot(@23, @29) */
  w26 = casadi_dot(1, (&w23), (&w29));
  /* #100: @26 = (@26/@3) */
  w26 /= w03;
  /* #101: @3 = project(@5) */
  casadi_sparsify(w05, (&w03), casadi_s9, 0);
  /* #102: @23 = dot(@3, @29) */
  w23 = casadi_dot(1, (&w03), (&w29));
  /* #103: @7 = (@7*@26) */
  w07 *= w26;
  /* #104: @23 = (@23-@7) */
  w23 -= w07;
  /* #105: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #106: @7 = @25[0] */
  for (rr=(&w07), cs=(&w25)+0; cs!=(&w25)+1; cs+=1) *rr++ = *cs;
  /* #107: @6 = (@6*@7) */
  w06 *= w07;
  /* #108: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #109: @6 = (-@6) */
  w06 = (- w06 );
  /* #110: @7 = project(@11) */
  casadi_sparsify(w11, (&w07), casadi_s9, 0);
  /* #111: @25 = dot(@7, @22) */
  w25 = casadi_dot(1, (&w07), (&w22));
  /* #112: @29 = dot(@22, @7) */
  w29 = casadi_dot(1, (&w22), (&w07));
  /* #113: @25 = (@25+@29) */
  w25 += w29;
  /* #114: @29 = dot(@3, @20) */
  w29 = casadi_dot(1, (&w03), (&w20));
  /* #115: @29 = (@29/@8) */
  w29 /= w08;
  /* #116: @13 = mac(@17,@20,@13) */
  casadi_mtimes(w17, casadi_s3, (&w20), casadi_s9, w13, casadi_s2, w, 0);
  /* #117: @20 = dot(@18, @13) */
  w20 = casadi_dot(2, w18, w13);
  /* #118: @20 = (@20/@10) */
  w20 /= w10;
  /* #119: @2 = (@2*@20) */
  w02 *= w20;
  /* #120: @29 = (@29-@2) */
  w29 -= w02;
  /* #121: @17 = vertcat(@27, @26, @23, @6, @25, @29) */
  rr=w17;
  *rr++ = w27;
  *rr++ = w26;
  *rr++ = w23;
  *rr++ = w06;
  *rr++ = w25;
  *rr++ = w29;
  /* #122: (@19[2, 6, 9, 10, 14, 17] = @17) */
  for (cii=casadi_s10, rr=w19, cs=w17; cii!=casadi_s10+6; ++cii, ++cs) rr[*cii] = *cs;
  /* #123: @27 = project(@0) */
  casadi_sparsify(w00, (&w27), casadi_s11, 0);
  /* #124: @26 = ones(18x1,1nz) */
  w26 = 1.;
  /* #125: {NULL, NULL, NULL, NULL, @23, NULL, NULL} = vertsplit(@26) */
  w23 = w26;
  /* #126: @26 = dot(@27, @23) */
  w26 = casadi_dot(1, (&w27), (&w23));
  /* #127: @26 = (@26/@1) */
  w26 /= w01;
  /* #128: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #129: @1 = @23[0] */
  for (rr=(&w01), cs=(&w23)+0; cs!=(&w23)+1; cs+=1) *rr++ = *cs;
  /* #130: @9 = (@9*@1) */
  w09 *= w01;
  /* #131: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #132: @9 = (-@9) */
  w09 = (- w09 );
  /* #133: @18 = vertcat(@26, @28, @28, @9, @28, @28) */
  rr=w18;
  *rr++ = w26;
  *rr++ = w09;
  /* #134: @13 = @18[:2] */
  for (rr=w13, cs=w18+0; cs!=w18+2; cs+=1) *rr++ = *cs;
  /* #135: (@19[3:19:8] = @13) */
  for (rr=w19+3, cs=w13; rr!=w19+19; rr+=8) *rr = *cs++;
  /* #136: output[1][0] = @19 */
  casadi_copy(w19, 18, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int rocket_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rocket_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rocket_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rocket_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rocket_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rocket_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rocket_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void rocket_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rocket_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int rocket_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real rocket_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rocket_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rocket_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rocket_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s12;
    case 1: return casadi_s13;
    case 2: return casadi_s14;
    case 3: return casadi_s14;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rocket_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s15;
    case 1: return casadi_s16;
    case 2: return casadi_s17;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rocket_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 10;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 100;
  return 0;
}

CASADI_SYMBOL_EXPORT int rocket_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 10*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 100*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
